.gitignore
babel.config.js
lerna.json
package.json
packages/button/package.json
packages/button/src/Component.tsx
packages/button/tsconfig.json
packages/react-app-env.d.ts
tsconfig.json
typings/module.d.ts
yarn.lock

Предлагаю добавить возможность сборки и публикации монорепозитория
Команда `publish:packages` должна собирать и публиковать пакеты , в которых были изменения, в https://www.npmjs.com/ .

Добавил возможность сборки и публикации монорепозитория

---

.editorconfig

Где - то в файлах есть пустая строка в конце, где - то её нету...
Везде должно быть одинаково

Вставка в конец всех файлов пустой строки

---

packages/divider/package.json
packages/divider/src/Component.module.css
packages/divider/src/Component.stories.tsx
packages/divider/src/Component.test.tsx
packages/divider/src/Component.tsx
packages/divider/src/index.module.css
packages/divider/src/index.ts
packages/divider/tsconfig.json

Компонент `Divider`

---

package.json
src/button/src/__snapshots__/Component.test.tsx.snap

- Исключил из тестов папки /dist
- Обновил снэпшот кнопки

fix(*): update scripts & snapshots

---

package.json
src/input/package.json
src/input/src/Component.test.tsx
src/input/src/__snapshots__/Component.test.tsx.snap
src/input/tsconfig.json
src/pure-input/package.json
src/pure-input/src/Component.test.tsx
src/pure-input/src/__snapshots__/Component.test.tsx.snap
src/pure-input/tsconfig.json

- Добавил тесты и снэпшоты для интутов, чтобы избежать ошибок
- Перенес @types/jest в devDependencies

fix(*): prepare inputs. move @types/jest to devDeps

---

babel.config.js
package.json

build(*): build to commonjs modules

---

.storybook/webpack.config.js
package.json

Добавить возможность быстрого запуска Storybook

---

CODE_OF_CONDUCT.md

chore(CODE_OF_CONDUCT.md): use russian version

---

README.md

Переписал ридми. Если что-то забыл - welcome 😉

docs(README.md): rewrite readme

---

package.json
yarn.lock

Обновил линтеры. Теперь нет ворнингов из https://github.com/alfa-laboratory/arui-presets-lint/issues/24

style(linters): update arui-presets-lint

---

src/amount/src/Component.tsx
src/button/src/Component.stories.tsx
src/button/src/Component.test.tsx
src/button/src/Component.tsx
src/divider/src/Component.stories.tsx
src/divider/src/Component.test.tsx
src/divider/src/Component.tsx
src/input/src/Component.stories.tsx
src/input/src/Component.test.tsx
src/input/src/Component.tsx
src/pure-input/src/Component.stories.tsx
src/pure-input/src/Component.test.tsx
src/pure-input/src/Component.tsx
src/utils/formatAmount.ts
src/utils/getCurrencySymbol.ts

https://github.com/alfa-laboratory/core-components/issues/72

chore(*): remove verbose comments

---

src/vars/src/index.css

- добавлен index.css, импортирующий все сущности пакета
- index.js оставлен, чтобы не ломать сборку. Будет удален после слияния https://github.com/alfa-laboratory/core-components/pull/87

feat(vars): add index.css

---

package.json
packages/button/package.json
packages/divider/package.json
packages/input/package.json
packages/masked-input/package.json
packages/pure-input/package.json
packages/switch/package.json
yarn.lock

https://github.com/alfa-laboratory/core-components/issues/91
- перенес classNames в peerDeps
- добавил text-mask-core зависимости корневого пакета
- перенес @storybook/preset-create-react-app в devDeps

fix(deps): fix wrong dependencies

---

packages/vars/src/gaps.css

Добавил переменные для негативных отступов

feat(vars): add negative gaps

---

packages/button/src/Component.stories.tsx
packages/button/src/index.module.css
packages/themes/click.css

* Обновлённые стили для соответствия макетам
* Темизация `ghost` и тема для Клика

Расширена темизация кнопки

---

packages/tag/src/Component.stories.tsx
packages/tag/src/Component.tsx
packages/tag/src/index.module.css

Изменена сигнатура `onClick` с целью единообразия компонентов

Change `onClick` signature

---

bin/build.sh

Файл `tsconfig.tsbuildinfo` писался в `dist`. Убрал его оттуда.

chore: remove tsconfig.tsbuildinfo from dist directory

---

packages/button/src/index.module.css

fix(core-components-button): iconOnly button min-width fix

---

rollup.config.js

[Issue](https://github.com/alfa-laboratory/core-components/issues/129)
Добавил имя папки в строку, от которой берется hash

build: add folder name to generating css classname hash

---

bin/build-root-package.sh
bin/build.sh
package.json
rollup.config.js
tools/core-components-resolver.js
yarn.lock

Были проблемы с путями в корневом пакете. Добавил резолвер, который корректно заменяет все взаимные импорты кор-компонентов.
Также, немного упрощена сборка css пакетов.

build: fix root build & small refactor

---

packages/button/src/Component.test.tsx
packages/button/src/Component.tsx

[Issue](https://github.com/alfa-laboratory/core-components/issues/135)
Заменил `Intersection` на `Union` в типах пропсов

feat(core-components-button): fix button types

---

packages/tag/src/Component.tsx
packages/tag/src/index.module.css

Пофиксил `background-color` у тэга. Теперь он `transparent` и не красится в серый цвет

fix(core-components-tag): fix tag background

---

.github/auto_assign.yml
packages/button/src/index.module.css

fix(core-components-button): fix block button width

---

packages/button/src/Component.stories.mdx
packages/button/src/Component.tsx
packages/button/src/__snapshots__/Component.test.tsx.snap
packages/checkbox-group/src/__snapshots__/Component.test.tsx.snap

Уехал loading после мерджа 🚗 
Будем форсить скриншот тесты :**(

fix(core-components-button): fix button loading state

---

tools/core-components-resolver.js

fix #170
Из-за лишнего флага в регулярке заменялись сразу всех схождения

fix: fix import replacement

---

packages/button/src/index.module.css

[Issue](https://github.com/alfa-laboratory/core-components/issues/177)

fix(core-components-button): disabled styles are back

---

postcss.config.js

fix: 🐛 use mixinsDir to import mixins

---

packages/tag/src/index.module.css

В IE контент в компоненте tag не центрируется по высоте

fix(tag): add height in ie (fix bug with flex and align-items)

---

packages/progress-bar/package.json
packages/progress-bar/src/Component.stories.mdx
packages/progress-bar/src/Component.test.tsx
packages/progress-bar/src/Component.tsx
packages/progress-bar/src/__snapshots__/Component.test.tsx.snap
packages/progress-bar/src/index.module.css
packages/progress-bar/src/index.ts
packages/progress-bar/tsconfig.json

Добавил компонент по этому [issue](https://github.com/alfa-laboratory/core-components/issues/195)

feat(core-components-progress-bar): add progress bar component

---

.storybook/addons/theme-switcher/index.css
.storybook/addons/theme-switcher/index.js
.storybook/addons/theme-switcher/register.js
.storybook/main.js
.storybook/preview.js
packages/amount-input/src/Component.stories.mdx
packages/amount/src/component.stories.mdx
packages/button/src/Component.stories.mdx
packages/form-control/src/Component.stories.mdx
packages/input/src/Component.stories.mdx
packages/masked-input/src/Component.stories.mdx
packages/pure-input/src/Component.stories.mdx
packages/select/src/Component.stories.mdx
packages/themes/src/mixins/click.css

feat: 🎸 add theme switcher to storybook

---

packages/progress-bar/src/index.module.css

В компоненте не используется дефолтная тема, в проекте не работает скругление у компонента

fix(core-components-progress-bar): use theme

---

lerna.json

Добавил сторисы и тесты в игнор лерны

chore: add lerna ignore

---

packages/tooltip/src/Component.tsx

Заметил, что timerId может обнулиться, заменил на реф

fix(core-components-tooltip): change tooltip timer to ref

---

package.json
packages/vars/src/typography.css
tools/update-typography.js
yarn.lock

Обновил alfa-ui-primitives и добавил миксины для новой типографики

feat(core-components-vars): add new typography styles

---

packages/phone-input/src/Component.tsx
packages/phone-input/tsconfig.json

Не проходила сборка
`yarn build`
Сборка проходит
Добавил в конфиг ts пути до либ, убрал  optional chaining

feat(core-components-phone-input): remove optional chaining

---

package.json
packages/button/package.json
packages/button/src/Component.test.tsx
packages/button/src/Component.tsx
packages/button/src/__snapshots__/Component.test.tsx.snap
packages/button/src/index.module.css
packages/vars/src/index.css
packages/vars/src/mixins.css
yarn.lock

Наконец-то затащили решение для клавиатурного фокуса. 
- Заюзал хук
- Убрал wrapper
- ~~_Надеюсь, что ничего не сломал_~~

refactor(core-components-button): use focus hook, remove wrapper

---

packages/phone-input/src/Component.tsx

fixes #247 
- Немного поменял скобки, добавив проверку previousConformedValue в оба кейса
- handleBeforeDisplay не был обернут в useCallback, что вызывало постоянный вызов createTextMaskInputElement

fix(core-components-phone-input): fix controlled value bug

---

packages/select/src/Component.stories.mdx
packages/select/src/components/autocomplete/Component.stories.mdx
packages/select/src/components/base-select/Component.tsx
packages/select/src/typings.ts

Закрывает https://github.com/alfa-laboratory/core-components/issues/240

refactor(core-components-select): use array of values as selected

---

packages/input/src/Component.test.tsx
packages/input/src/Component.tsx
packages/masked-input/src/Component.stories.mdx
packages/masked-input/src/Component.test.tsx
packages/masked-input/src/Component.tsx
packages/masked-input/src/index.module.css
packages/textarea/src/Component.test.tsx
packages/textarea/src/Component.tsx

1. Отрефакторил filled состояние в инпуте и textarea. Сделал +- так же, как в фижере. Теперь controlled и uncontrolled кейсы отрабатывают правильно. <br><img src="https://user-images.githubusercontent.com/9968618/91714028-8b6b3400-eb93-11ea-98f3-d5c296a6d846.png" width="320" />
2. Пофиксил defaultValue в инпуте и textarea
3. Пофиксил masked-input. Т.к. в данный момент controlled-way работает неправильно
4. Добавил под это все тесты
5. Обновил сторисы

refactor: correct values handling

---

packages/themes/src/mixins/amount/click.css

Когда делали компонент amount минорные единицы были тонкие, сейчас они стали жирные, как и основные единицы.

chore: edit minor font-weight

---

packages/tag/src/index.module.css

Добавлена минимальная ширина для Tag

feat(core-components-tag): min-width for tags

---

.storybook/addons/theme-switcher/index.css
.storybook/addons/theme-switcher/register.js
package.json
packages/button/src/Component.stories.mdx
packages/button/src/Component.tsx
packages/button/src/index.module.css
packages/themes/src/mixins/button/click.css
packages/themes/src/mixins/button/corp.css
packages/themes/src/mixins/button/mobile.css
packages/themes/src/mixins/corp.css
packages/themes/src/mixins/mobile.css
packages/themes/src/mixins/site.css
packages/vars/src/colors-indigo.css
yarn.lock

* Изменена высота кнопки в размере l (68→72)
* Обновлена тема для Клика
* Добавлена тема для НИБ (corp)
* Добавлена тема для мобайла/вебвью (mobile)
* Добавлен вид filled для тех у кого secondary кнопки имеют вид outlined

feat(core-components-button): updated styles/themes and filled view

---

packages/select/src/components/autocomplete-field/Component.tsx

fix(core-components-select): remove default autocomplete

---

packages/amount-input/src/Component.tsx

feat(core-components-amount-input): add forward ref

---

packages/amount-input/src/Component.stories.mdx
packages/amount-input/src/Component.tsx

Пофиксил ошибку в консоли: `Warning: Received 'true' for a non-boolean attribute 'clear'`

fix(core-components-amount-input): fix console error

---

packages/vars/src/shadows-indigo.css

Пять уровней теней.
Hard — более контрастные тени для тёмных плашек.

feat(core-components-vars): introducing shadows vars

---

packages/amount-input/src/Component.tsx
packages/amount-input/src/__snapshots__/Component.test.tsx.snap
packages/amount-input/src/index.module.css

fix(core-components-amount-input): resolve #281

---

packages/input-autocomplete/package.json
packages/input-autocomplete/src/Component.stories.mdx
packages/input-autocomplete/src/Component.tsx
packages/input-autocomplete/src/autocomplete-field/Component.tsx
packages/input-autocomplete/src/autocomplete-field/index.ts
packages/input-autocomplete/src/index.ts
packages/input-autocomplete/tsconfig.json
packages/select/src/components/field/Component.tsx
packages/select/src/components/index.ts
packages/select/src/index.ts

- Autocomplete -> InputAutocomplete
- Вынес в отдельный пакет
- Правки экспортов в селекте

refactor(core-components-input-autocomplete): move component

---

package.json
packages/vars/src/colors-addons.css
yarn.lock

feat(core-components-vars): updated colors addons

---

packages/bank-card/src/index.module.css

Сделал каретку черной 💪 
Пока цвет каретки меняем только тут

feat(core-components-bank-card): change caret color

---

packages/bank-card/src/Component.stories.mdx
packages/bank-card/src/Component.test.tsx
packages/bank-card/src/Component.tsx
packages/bank-card/src/__snapshots__/Component.test.tsx.snap
packages/bank-card/src/index.module.css

> Ребят, есть следующий кейс: для компонента BankCard  мы используем сканер карты с помощью камеры, после сканирования номер карты подставляется в нужный пропс и попадает в инпут компонента, проблема в том, что в нем подстановка платежной системы осуществляется по onChange , а у нас его не происходит.
- Также, после обновления инпута, получилось убрать лишний код
- Добавил тестов
- Обновил стори

refactor(core-components-bank-card): brand detection, refactor

---

packages/bank-card/src/Component.tsx

fixed #308 
Хотел добавить тесты, но userEvent коряво работает с кареткой и воспроизвести баг не получается.

fix(core-components-bank-card): deleting issue, add useCallback

---

packages/form-control/src/index.module.css
packages/themes/src/mixins/form-control/click.css
packages/themes/src/mixins/pure-input/click.css

feat(core-components-input): updated input click theme

---

packages/tabs/src/components/primary-tablist/index.module.css
packages/tabs/src/components/primary-tablist/mobile.module.css
packages/tabs/src/vars.css
packages/themes/src/mixins/tabs/click.css

Верхний отступ в табах нужен только в Клике, выносим в тему

Tabs padding

---

packages/tabs/package.json
packages/tabs/src/Component.stories.mdx
packages/tabs/src/components/index.ts
packages/tabs/src/components/primary-tablist/Component.responsive.tsx
packages/tabs/src/components/primary-tablist/index.module.css
packages/tabs/src/components/primary-tablist/index.ts
packages/tabs/src/components/primary-tablist/mobile.module.css
packages/tabs/src/components/secondary-tablist/Component.responsive.tsx
packages/tabs/src/components/secondary-tablist/index.ts
packages/tabs/src/components/secondary-tablist/mobile.module.css
packages/tabs/src/components/tabs/Component.desktop.tsx
packages/tabs/src/components/tabs/Component.mobile.tsx
packages/tabs/src/components/tabs/Component.responsive.tsx
packages/tabs/src/components/tabs/Component.test.tsx
packages/tabs/src/components/tabs/index.ts
packages/tabs/src/desktop.ts
packages/tabs/src/index.ts
packages/tabs/src/mobile.ts
packages/tabs/src/responsive.ts
packages/tabs/src/useTabs.test.tsx
packages/tabs/src/vars.css
packages/themes/src/mixins/tabs/click.css

1. В сборку попадали стили без префиксов
2. Из-за индексных файлов импортировались сразу все версии компонентов, вместе со стилями.
1. Удалил импорты из css файлов, заюзал composes
2. Удалил индексные файлы, теперь компоненты нужно импортировать явно:
```tsx
import { TabsDesktop, Tab } from '@alfalab/core-components/tabs/desktop';
```

fix(core-components-tabs): fix styles build

---

packages/confirmation/src/component.stories.mdx
packages/confirmation/src/components/code-input/component.tsx
packages/confirmation/src/components/code-input/index.module.css
packages/confirmation/src/components/countdown-loader/component.tsx
packages/confirmation/src/components/countdown-loader/index.module.css
packages/confirmation/src/components/countdown/component.tsx
packages/confirmation/src/components/countdown/index.module.css
packages/confirmation/src/components/sign-confirmation/index.module.css
packages/confirmation/src/index.module.css
packages/confirmation/src/vars.css
packages/themes/src/mixins/click.css
packages/themes/src/mixins/confirmation/click.css

feat(core-components-confirmation): fixes

---

packages/form-control/src/index.module.css

fix(core-components-form-control): fix hover state

---

packages/form-control/src/Component.test.tsx
packages/form-control/src/Component.tsx
packages/input/src/Component.test.tsx
packages/input/src/Component.tsx

Добавил доп. классы для аддонов - бывает нужно убрать отступы

feat(core-components-form control): addons classname

---

packages/bank-card/src/index.module.css

Лейбл теперь меняется с 20px -> 16px

fix(core-components-bank-card): label styles

---

packages/badge/package.json
packages/badge/src/Component.stories.mdx
packages/badge/src/Component.test.tsx
packages/badge/src/Component.tsx
packages/badge/src/__snapshots__/Component.test.tsx.snap
packages/badge/src/index.module.css
packages/badge/src/index.ts
packages/badge/tsconfig.json

#327
Добавлен новый компонент Badge

feat(core-components-badge): add component

---

packages/confirmation/src/component.stories.mdx
packages/confirmation/src/components/code-input/component.tsx

fix(core-components-confirmation): fix showed keyboard on old devices

---

packages/link/src/Component.stories.mdx
packages/link/src/Component.test.tsx
packages/link/src/Component.tsx
packages/link/src/__snapshots__/Component.test.tsx.snap
packages/link/src/index.module.css
yarn.lock

Добавляет слоты для компонента Link по аналогии с Button

feat(core-components-link): add slots

---

packages/list-header/package.json
packages/list-header/src/Component.stories.mdx
packages/list-header/src/Component.test.tsx
packages/list-header/src/Component.tsx
packages/list-header/src/__snapshots__/Component.test.tsx.snap
packages/list-header/src/index.module.css
packages/list-header/src/index.ts
packages/list-header/tsconfig.json

Добавляет новый компонент ListHeader
[Issue#339](https://github.com/alfa-laboratory/core-components/issues/339)

feat(core-components-list-header): add component

---

packages/select/src/Component.stories.mdx
packages/select/src/__snapshots__/Component.test.tsx.snap
packages/select/src/components/arrow/Component.tsx
packages/select/src/components/arrow/index.module.css
packages/select/src/components/base-select/Component.tsx
packages/select/src/components/base-select/index.module.css
packages/select/src/components/field/Component.tsx
packages/select/src/components/field/index.module.css
packages/select/src/components/options-list/index.module.css
packages/select/src/components/virtual-options-list/Component.tsx
packages/select/src/components/virtual-options-list/index.module.css
packages/select/src/typings.ts
packages/select/src/utils.test.tsx
packages/select/src/utils.ts
packages/select/src/vars.css
packages/themes/src/mixins/select/click.css

- Добавил управление открытием
- Возможность добавить что-то до\после выпадающего списка
- Убрал лишний проход по списку
- Мелкие фиксы

refactor(core-components-select): newclick integration fixes and improvements

---

packages/vars/src/breakpoints.css
packages/vars/src/index.css

Перенес из фижера переменные для брейкпоинтов

feat(core-components-vars): add breakpoints

---

commitlint.config.js

ci: changed config-lerna-scopes rules

---

packages/plate/src/Component.tsx

fix(plate): remove redunadant className

---

packages/button/src/Component.test.tsx
packages/button/src/Component.tsx
packages/button/src/__snapshots__/Component.test.tsx.snap
packages/button/src/index.module.css

fix(button): show loader when href is set

---

packages/select/src/vars.css

У селекта теперь специальная иконка для стрелки \*_\*

feat(select): change arrow icon

---

packages/form-control/src/index.module.css

[Тут](https://github.com/alfa-laboratory/core-components/pull/345) проглядел, что высота контролов из-за фикса выросла на 1px :(
Надеюсь, никому ничего не сломало. 
Есть идеи, как это пофиксить лучше?

fix(form-control): fix height

---

packages/checkbox/src/Component.stories.mdx
packages/checkbox/src/index.module.css
packages/radio/src/Component.stories.mdx
packages/radio/src/index.module.css
packages/switch/src/Component.stories.mdx
packages/switch/src/index.module.css
packages/themes/src/mixins/checkbox/click.css
packages/themes/src/mixins/click.css
packages/themes/src/mixins/radio/click.css
packages/themes/src/mixins/switch/click.css

Экспериментальная тема для checkbox/radio/switch и небольшой рефакторинг в стилях для единообразия

feat(themes): click theme for checkbox/radio/switch

---

.storybook/addons/theme-switcher/index.css
.storybook/addons/theme-switcher/index.js
.storybook/addons/theme-switcher/register.js

Теперь переключалка темы запоминает выбор между историями и докой

feat: improve theme switcher

---

packages/confirmation/src/components/code-input/component.tsx

Пофиксил проблему при удалении символов, которая почему-то не воспроизводилась в демке, только на проекте у Клика

fix(confirmation): fix symbols deleting

---

packages/select/src/components/base-select/index.module.css
packages/select/src/vars.css

feat(select): change optionslist shadow styles

---

packages/popover/src/Component.tsx
packages/select/src/components/base-select/Component.tsx

http://jira.moscow.alfaintra.net/browse/NEWCLICK-1845
Хотят опцию, при которой поповер будет открываться только вниз

feat(popover): prevent flip

---

packages/button/src/index.module.css
packages/checkbox/src/index.module.css
packages/input/src/index.module.css
packages/intl-phone-input/src/component.stories.mdx
packages/intl-phone-input/src/component.tsx
packages/intl-phone-input/src/components/select-field/component.tsx
packages/intl-phone-input/src/components/select-field/index.module.css
packages/pure-input/src/index.module.css
packages/radio/src/index.module.css
packages/select/src/components/field/index.module.css
packages/select/src/components/option/index.module.css
packages/slider/src/index.module.css
packages/switch/src/index.module.css
packages/tag/src/index.module.css
packages/textarea/src/index.module.css
packages/themes/src/default.css
packages/themes/src/mixins/click.css

- Добавил переменную с курсором для disabled состояний
- Заюзал ее в компонентах
- Добавил disabled для IntlPhoneInput
---
readOnly будет отдельным PR

feat: use disabled-cursor

---

packages/input-autocomplete/src/Component.tsx
packages/popover/src/Component.stories.mdx
packages/popover/src/Component.tsx
packages/select/src/components/base-select/Component.tsx
packages/select/src/typings.ts
packages/tooltip/src/Component.tsx

Добавил в компонент `Popover` пропсу `update`, в которой хранится функция для обновления компонента.
Если есть более удачные варианты наименования - предлагайте)
Также прокинул эту пропсу во все компоненты, где юзается поповер.

feat: add update popover position prop

---

.storybook/addons/theme-switcher/index.css
.storybook/public/global.css
packages/button/src/Component.stories.mdx
packages/button/src/index.module.css
packages/link/src/Component.stories.mdx
packages/themes/src/mixins/button/corp-inverted.css
packages/themes/src/mixins/corp-inverted.css
packages/themes/src/mixins/default-inverted.css
packages/themes/src/mixins/link/corp-inverted.css
packages/themes/src/mixins/link/default-inverted.css

Инвертированные темы для primary ссылки и secondary кнопки у corp (которая выглядит как outline 🤯)
Добавлял только то, что нужно. Движемся итеративненько ))

feat: add inverted theme for link & button

---

packages/picker-button/package.json
packages/picker-button/src/Component.stories.mdx
packages/picker-button/src/Component.test.tsx
packages/picker-button/src/Component.tsx
packages/picker-button/src/__snapshots__/Component.test.tsx.snap
packages/picker-button/src/field/Component.tsx
packages/picker-button/src/field/index.module.css
packages/picker-button/src/field/index.ts
packages/picker-button/src/index.module.css
packages/picker-button/src/index.ts
packages/picker-button/tsconfig.json

добавил компонент PickerButton
[ишью](https://github.com/alfa-laboratory/core-components/issues/407)
[дизайн](https://www.figma.com/file/uGndMZufgvqxaNQTaNTEjG/B2B-Web-Components?node-id=1167%3A13307)

feat(picker-button): add compoonent PickerButton

---

packages/button/src/Component.tsx
packages/button/src/index.module.css
packages/notification/src/__snapshots__/Component.test.tsx.snap

Не растягивался контент внутри кнопки на всю её ширину
Растягивание на всю ширину

Add css to button

---

packages/button/src/index.module.css
packages/themes/src/mixins/button/corp.css

Just some design review css fixes
_Trust me_

fix(button): design review fixes

---

packages/vars/src/shadows-indigo.css

Обновление теней из [alfa-ui-primitives](https://github.com/alfa-laboratory/alfa-ui-primitives/blob/master/styles/shadows_indigo.json)
[Тени в фигме](https://www.figma.com/file/5rA88VickeSHbBl7mTaR7J/Colors-Indigo-Light?node-id=2645%3A594)

feat(vars): new reverse shadows

---

packages/slider-input/src/Component.tsx
packages/slider-input/src/__snapshots__/Component.test.tsx.snap

Показываем на мобилках цифровую клавиатуру

feat(slider-input): use numeric mobile keyboard

---

packages/loader/src/index.module.css
packages/picker-button/src/__snapshots__/Component.test.tsx.snap
packages/picker-button/src/field/Component.tsx
packages/picker-button/src/field/index.module.css

[Обновлённая анимация](https://www.figma.com/file/KlFOLLkKO8rtvvQE3RXuhq/Click-Library?node-id=15790%3A55398) лоадера
Upd: включает фикс PickerButton, у которого пропустили глобальный стиль, влиявший на loading в Button

feat(loader): updated loader animation

---

packages/picker-button/src/Component.stories.mdx
packages/picker-button/src/Component.test.tsx
packages/picker-button/src/Component.tsx
packages/picker-button/src/__snapshots__/Component.test.tsx.snap
packages/picker-button/src/field/Component.tsx

- Возможность позиционирования меню
- Убрал левые пропсы из DOM и типов
- Пофиксил тесты (убрал бесячие ворнинги)

refactor(picker-button): popover position, tests and fixes

---

packages/calendar-input/src/Component.tsx
packages/calendar-input/src/__snapshots__/Component.test.tsx.snap
packages/calendar-input/src/index.module.css
packages/calendar/src/components/select-button/index.module.css
packages/calendar/src/index.module.css

- Поправил паттерн
- Заимпортил переменные там, где забыл

fix(calendar): wrong pattern, vars import

---

packages/select/src/index.ts

feat(select): add exporting select utils

---

packages/bank-card/src/index.module.css
packages/form-control/src/index.module.css
packages/pure-input/src/index.module.css
packages/textarea/src/Component.tsx
packages/textarea/src/index.module.css
packages/themes/src/mixins/form-control/click.css
packages/themes/src/mixins/form-control/site.css
packages/themes/src/mixins/site.css

- изменил стили обводки — вынес ее в псевдоэлемент. Теперь контент контрола занимает всю высоту. Раньше 2px съедалось
- изменил стили label'а, теперь он позиционируется более предсказуемо. Убрал изменение font-size, заменил на scale

feat: change form-control styles

---

packages/typography/src/component.stories.mdx
packages/typography/src/margins.module.css
packages/typography/src/title-responsive/component.tsx
packages/typography/src/title-responsive/index.module.css
packages/typography/src/title/component.tsx
packages/typography/src/title/index.module.css
packages/typography/src/title/index.tsx

Добавил отступы для заголовков

feat(typography): add default margins

---

packages/select/src/components/base-select/Component.tsx

клик по инпуту не должен скрывать поповер

feat(input-autocomplete): dont close popover on input click

---

jest.config.js
packages/calendar/src/__snapshots__/Component.test.tsx.snap
packages/globalSetup.ts

Фикс тестов при запуске в таймзоне, отличной от Мск

fix(calendar): snapshots timezone issue

---

packages/calendar-input/src/Component.tsx
packages/calendar-range/package.json
packages/calendar-range/src/Component.stories.mdx
packages/calendar-range/src/Component.test.tsx
packages/calendar-range/src/Component.tsx
packages/calendar-range/src/__snapshots__/Component.test.tsx.snap
packages/calendar-range/src/index.module.css
packages/calendar-range/src/index.ts
packages/calendar-range/src/utils.ts
packages/calendar-range/tsconfig.json
packages/calendar/src/usePeriod.ts

feat(calendar-range): add component

---

packages/divider/src/index.module.css

Забыли поменять импорт, в итоге не все нужные переменные попадали в сборку

fix(divider): missed vars

---

packages/select/src/components/option/index.module.css
packages/themes/src/mixins/select/click.css

В теме Клика пофикшен размер иконки выбранного опшена и транзишн разделителя

fix(themes): fixed click select theme

---

packages/link/src/Component.stories.mdx
packages/link/src/Component.tsx
packages/link/src/__snapshots__/Component.test.tsx.snap
packages/link/src/index.module.css

Добавляет разметку для слотов (leftAddons/rightAddons) только при необходимости
Closes #406

feat(link): simplify link without addons

---

packages/tabs/src/Component.stories.mdx
packages/tabs/src/vars.css
packages/themes/src/mixins/corp.css
packages/themes/src/mixins/tabs/corp.css

Православный цвет разделителя у табов

feat(themes): updated tabs border colors

---

packages/themes/src/mixins/tag/click.css

В теме Клика убран лишний ховер для выбранного состояния

feat(themes): fixed click theme for tag

---

packages/picker-button/src/field/index.module.css
packages/plate/src/index.module.css
packages/select/src/components/arrow/index.module.css
packages/themes/src/default.css
packages/themes/src/mixins/click.css

Переменная определяющая `transform` поворота стрелок в компонентах Select/Plate

feat(themes): --arrow-transform var with click theme

---

packages/space/src/Component.tsx
packages/space/src/__snapshots__/Component.test.tsx.snap

В компоненте `Space` есть `div` на который не вешается никакой класс и только мешает в разработке. Возможно его забыли удалить при разработке самого компонента.

fix(space): removed excess div

---

packages/amount-input/src/Component.stories.mdx
packages/calendar-input/src/Component.stories.mdx
packages/calendar-input/src/Component.tsx
packages/calendar-range/src/Component.test.tsx
packages/calendar-range/src/__snapshots__/Component.test.tsx.snap
packages/input-autocomplete/src/Component.tsx
packages/input-autocomplete/src/autocomplete-field/Component.tsx
packages/input/src/Component.stories.mdx
packages/input/src/index.module.css
packages/intl-phone-input/src/component.stories.mdx
packages/intl-phone-input/src/component.tsx
packages/slider-input/src/Component.stories.mdx
packages/slider-input/src/Component.tsx
packages/textarea/src/Component.stories.mdx
packages/textarea/src/index.module.css
packages/themes/src/default.css
packages/themes/src/mixins/input/click.css
packages/with-suffix/src/Component.stories.mdx
packages/with-suffix/src/Component.tsx
packages/with-suffix/src/index.module.css

- проработан read-only
- фикс цветов в теме клика при disabled

feat: read-only state

---

packages/amount/src/component.stories.mdx

Изменил описание и расположение.
Было:
Стало:

Поправил стори для Amount

---

packages/bank-card/src/__snapshots__/Component.test.tsx.snap
packages/input/src/Component.test.tsx
packages/input/src/Component.tsx

fix(input): set aria-label attr when label passed

---

packages/calendar/src/components/years-table/index.module.css

Пофиксил неправильное положение списка годов

fix(calendar): fix years-table position

---

packages/calendar/src/Component.tsx
packages/calendar/src/components/years-table/Component.tsx

Пролистывание до выбранного года при открытии списка с годами в календаре

feat(calendar): add scrolling to selected year when open year select

---

packages/input-autocomplete/src/autocomplete-field/Component.tsx

убрал ненужный preventDefault
https://trello.com/c/ECYD2AMy/564-inputautocomplete-%D0%B2%D0%BE%D0%B7%D0%BC%D0%BE%D0%B6%D0%BD%D0%BE%D1%81%D1%82%D1%8C-%D0%B2%D1%8B%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F-%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D1%8F

fix(input-autocomplete): fix mousedown issue

---

packages/form-control/src/index.module.css
packages/select/src/components/base-select/index.module.css

fix style for form-control and base-select

---

packages/checkbox-group/src/__snapshots__/Component.test.tsx.snap
packages/checkbox/src/Component.stories.mdx
packages/checkbox/src/Component.tsx
packages/checkbox/src/__snapshots__/Component.test.tsx.snap
packages/checkbox/src/index.module.css
packages/radio-group/src/__snapshots__/Component.test.tsx.snap
packages/radio/package.json
packages/radio/src/Component.stories.mdx
packages/radio/src/Component.tsx
packages/radio/src/__snapshots__/Component.test.tsx.snap
packages/radio/src/index.module.css
packages/switch/src/Component.stories.mdx
packages/switch/src/Component.tsx
packages/switch/src/__snapshots__/Component.test.tsx.snap
packages/switch/src/index.module.css

Небольшой апдейт для компонента, добавил опциональную функциональность

feat: improve radio, checkbox and switch components

---

package.json
packages/badge/src/index.module.css
packages/bank-card/src/index.module.css
packages/calendar/src/components/days-table/index.module.css
packages/calendar/src/components/header/index.module.css
packages/skeleton/src/stories.module.css
packages/tag/src/index.module.css
yarn.lock

впилил [линтер](https://github.com/alfa-laboratory/stylelint-core-vars) и прогнал по нему.
Пока заменяет только точные замены

feat: add stylelint-core-vars

---

.github/workflows/npm-publish.yml

ограничение на 5 пакетов одновременной сборки

chore: add build concurrency

---

packages/tag/src/Component.tsx

Для проверки работоспособности semantic-release

fix(tag): fix formatting

---

rollup.config.js

Заметил, что в последнюю сборку попали скриншоты компонентов 🙈

build: remove screenshots from build

---

packages/amount-input/src/Component.test.tsx
packages/amount-input/src/Component.tsx
packages/amount-input/src/utils/index.ts

При передаче в компонент количества денег с нулевыми минорными единицами они будут удаляться.

feat(amount-input): delete zero minor part in passed amount

---

packages/phone-input/src/Component.tsx

Неправильное поведение каретки при редактировании номера телефона.
https://user-images.githubusercontent.com/32348899/106278840-754dc680-624c-11eb-8fff-c7f803048ad1.mov
При вводе числа кареткад должна вставать за ним.

fix(phone-input): fix caret

---

packages/switch/src/index.module.css

fix(switch): box-sizing issue

---

docs/2.theming.stories.mdx

Кажется лишний символ `~`в импорте.

docs: theming.stories.mdx

---

package.json
packages/amount-input/package.json
packages/amount-input/src/Component.tsx
packages/amount/package.json
packages/amount/src/pure/component.tsx
packages/attach/package.json
packages/intl-phone-input/package.json
tools/update-colors.js
yarn.lock

Подтянул и уравнял зависимости `@alfalab/data` и `@alfalab/utils`

chore: update data and utils dependencies

---

packages/badge/src/Component.stories.mdx
packages/badge/src/Component.test.tsx
packages/modal/src/Component.tsx
packages/plate/src/Component.stories.mdx
packages/plate/src/Component.test.tsx
packages/select-with-tags/src/components/tag-list/component.tsx

Привёл импорт иконок к одному виду

refactor: update icon import

---

bin/demo-build.js

Теперь демка открывается сразу на нужном компоненте

feat: smart demo link

---

packages/calendar-range/src/Component.stories.mdx
packages/calendar/src/Component.tsx
packages/calendar/src/__snapshots__/Component.test.tsx.snap
packages/calendar/src/components/days-table/index.module.css
packages/calendar/src/useCalendar.ts
packages/themes/src/mixins/calendar-input/click.css
packages/themes/src/mixins/click.css

- поправил стори
- пофиксил стиль disabled + selected
- убрал ограничение на 100 лет, если minDate не задан
- иконка с теме клика

fix(calendar): fixes

---

packages/form-control/src/index.module.css
packages/select-with-tags/src/components/tag-list/index.module.css

```
Цвет текста text/primary, сейчас чёрный.
```
Нужно отдельно заняться выносом и причесыванием общих переменных

fix: control colors (PDS-199)

---

packages/input-autocomplete/src/autocomplete-field/Component.tsx
packages/input/src/Component.tsx
packages/input/src/index.module.css
packages/with-suffix/src/index.module.css

Фиксы read-only состояния контролов

feat: improve read-only behaviour (PDS-200)

---

packages/themes/src/mixins/link/corp-inverted.css

fix(themes): corp theme

---

packages/plate/src/index.module.css
packages/themes/src/default.css

* Поправлена переменная для поворота стрелок `--arrow-transform`
* Немного ускорена анимация раскрытия плашек

fix(plate): fixed --arrow-transform var, tuned transition

---

packages/icon-button/package.json
packages/icon-button/src/Component.stories.mdx
packages/icon-button/src/Component.test.tsx
packages/icon-button/src/Component.tsx
packages/icon-button/src/__snapshots__/Component.test.tsx.snap
packages/icon-button/src/index.module.css
packages/icon-button/src/index.ts
packages/icon-button/tsconfig.json

https://www.figma.com/file/KlFOLLkKO8rtvvQE3RXuhq/Click-Library?node-id=21264%3A120061

feat(icon-button): add component

---

packages/button/src/Component.stories.mdx
packages/button/src/index.module.css
packages/themes/src/mixins/toast-plate/click.css
packages/toast-plate/src/component.tsx
packages/toast-plate/src/index.module.css

* Темизация кнопки в тосте.
* Фикс выравнивания после обновления Badge.
* Фикс line-height у Button (1.2 → 20/24), теперь по сетке.

feat(toast-plate): add action button theming, fix addons align

---

packages/amount-input/package.json
packages/amount/package.json
packages/attach/package.json
packages/badge/package.json
packages/button/package.json
packages/calendar-range/package.json
packages/calendar/package.json
packages/checkbox-group/package.json
packages/form-control/package.json
packages/input-autocomplete/package.json
packages/input/package.json
packages/intl-phone-input/package.json
packages/notification/package.json
packages/phone-input/package.json
packages/plate/package.json
packages/popover/package.json
packages/radio-group/package.json
packages/select-with-tags/package.json
packages/select/package.json
packages/switch/package.json
packages/themes/package.json
packages/toast-plate/package.json
packages/with-suffix/package.json

Обновил версии всех компонентов в соответствии с версиями из npm

fix: update versions

---

packages/tabs/src/Component.stories.mdx
packages/tabs/src/components/primary-tablist/Component.tsx
packages/tabs/src/components/primary-tablist/index.module.css
packages/tabs/src/components/tab/Component.tsx
packages/tabs/src/components/tabs/Component.tsx
packages/tabs/src/components/tabs/__snapshots__/Component.test.tsx.snap
packages/tabs/src/typings.ts
packages/tabs/src/useTabs.tsx
packages/tabs/src/vars.css

feat(tabs): disabled view

---

package.json
packages/badge/src/Component.stories.mdx
packages/themes/src/mixins/colors/colors-indigo.css
packages/vars/src/colors-indigo.css
packages/vars/src/typography.css
yarn.lock

Обновил alfa-ui-primitives и icons-glyph, причесал демку badge (PDS-193)

feat: updated design tokens

---

packages/picker-button/src/__snapshots__/Component.test.tsx.snap
packages/select/src/Component.stories.mdx
packages/select/src/components/base-select/Component.tsx
packages/select/src/components/options-list/Component.tsx
packages/select/src/components/options-list/index.module.css
packages/select/src/components/virtual-options-list/Component.tsx
packages/select/src/components/virtual-options-list/index.module.css
packages/select/src/typings.ts
packages/select/src/utils.ts
packages/select/src/vars.css

добавил пропсу для управления кол-во видимых пунктов

feat(select): add visible-options

---

packages/themes/src/mixins/click.css
packages/themes/src/mixins/list/click.css

Темизация в полный рост (PDS-205)

feat(themes): list click theme

---

packages/button/src/Component.test.tsx
packages/button/src/Component.tsx

Добавление атрибута rel='noopener noreferrer' для кнопки которой передан href и target='_blank'

feat(button): add rel='noopener noreferrer' if target='blank'

---

packages/link/src/Component.test.tsx
packages/link/src/Component.tsx

feat(link): set rel='noreferrer noopener' if target='_blank'

---

packages/select-with-tags/src/__snapshots__/component.test.tsx.snap
packages/select-with-tags/src/components/tag-list/component.tsx
packages/select-with-tags/src/components/tag-list/index.module.css

Поправлены стили для размеров s, m
Поправлены стили чтобы при добавлении тегов не менялась высота инпута

fix(select-with-tags): fixed styles

---

packages/checkbox/src/index.module.css
packages/grid/src/gutters.module.css
packages/plate/src/index.module.css
packages/radio/src/index.module.css
packages/toast-plate/src/index.module.css
packages/vars/src/gaps.css

feat(vars): 2px gap

---

packages/toast/src/__snapshots__/component.test.tsx.snap
packages/toast/src/component.test.tsx

test(toast): add tests

---

packages/intl-phone-input/src/component.stories.mdx
packages/intl-phone-input/src/component.test.tsx
packages/intl-phone-input/src/component.tsx
yarn.lock

fix #518
Добавлен обработчик события изменения страны.

feat(intl-phone-input): add onCountryChange handler

---

packages/confirmation/src/vars.css
packages/themes/src/mixins/confirmation/click.css

Сейчас в теме клик неправильный набор у заголовка.
Добавил свойство `font-feature-settings`.

fix(confirmation): add font feature settings

---

packages/picker-button/src/__snapshots__/Component.test.tsx.snap
packages/popover/src/Component.stories.mdx
packages/popover/src/Component.test.tsx
packages/popover/src/Component.tsx
packages/popover/src/__snapshots__/Component.test.tsx.snap
packages/popover/src/index.module.css
packages/toast/src/component.tsx
packages/tooltip/src/__snapshots__/Component.test.tsx.snap
yarn.lock

Изменил анимацию у компонента `Popover` [согласно гайдланам](https://www.figma.com/file/KlFOLLkKO8rtvvQE3RXuhq/Click-Library?node-id=20655%3A0):
- время анимации 150ms
- scale 98% -> 100%
- opacity: 0 -> 1
`Popover` используется в компонентах `Toast` и `Tooltip`, так что анимация там тоже обновилась.
**BREAKING CHANGE: Изменена html-структура компонента.**
**Так как реквест содержит BREAKING CHANGE, то для корректного определения новых версий компонентов, его нужно мержить без сквоша!**

feat(popover): change animation

---

packages/icon-button/src/Component.stories.mdx
packages/themes/src/mixins/default-inverted.css
packages/themes/src/mixins/icon-button/default-inverted.css

[inverted](https://www.figma.com/file/KlFOLLkKO8rtvvQE3RXuhq/Click-Library?node-id=21264%3A120061) тема

feat(icon-button): inverted theme

---

.github/workflows/screenshots.yml
packages/select/src/__image_snapshots__/select-interactions-tests-open-select-select-one-item-1-snap.png
packages/select/src/__image_snapshots__/select-interactions-tests-open-select-select-one-item-2-snap.png
packages/select/src/__image_snapshots__/select-interactions-tests-open-select-select-one-item-3-snap.png
packages/select/src/component.screenshots.test.tsx
packages/utils/helpers.ts
packages/utils/screenshot-testing.ts

1. Сохраняем диффы зафейленных скриншотов в артефакты
2. Обновил тест и скриншоты

chore: screenshots diffs artefacts

---

packages/picker-button/src/__snapshots__/Component.test.tsx.snap
packages/popover/src/index.module.css
packages/select/package.json
packages/select/src/components/base-select/Component.tsx
packages/select/src/components/base-select/index.module.css
packages/toast/src/__snapshots__/component.test.tsx.snap
packages/toast/src/component.stories.mdx
packages/toast/src/component.tsx
packages/toast/src/index.module.css
yarn.lock

- Мы еще не реализовали систему z-index'ов, так что пока увеличил z-index тоста до 9999
- Удалил лишнюю очистку таймера
- Пофиксил z-index в селекте

fix(toast): remove extra timer clearing

---

packages/attach/src/__snapshots__/Component.test.tsx.snap
packages/button/src/Component.test.tsx
packages/button/src/Component.tsx
packages/button/src/__snapshots__/Component.test.tsx.snap
packages/calendar-range/src/__snapshots__/Component.test.tsx.snap
packages/calendar/src/__snapshots__/Component.test.tsx.snap
packages/confirmation/src/__snapshots__/Component.test.tsx.snap
packages/icon-button/src/__snapshots__/Component.test.tsx.snap
packages/notification/src/__snapshots__/Component.test.tsx.snap
packages/picker-button/src/__snapshots__/Component.test.tsx.snap

Ставим всем кнопкам `type="button"` по-умолчанию

fix(button): set type button by default

---

README.md
packages/badge/src/index.module.css
packages/bank-card/src/index.module.css
packages/button/src/index.module.css
packages/calendar-input/src/index.module.css
packages/calendar/src/components/days-table/index.module.css
packages/calendar/src/components/select-button/index.module.css
packages/calendar/src/vars.css
packages/card-image/src/index.module.css
packages/checkbox/src/index.module.css
packages/confirmation/src/components/code-input/index.module.css
packages/modal/src/vars.css
packages/plate/src/index.module.css
packages/progress-bar/src/index.module.css
packages/radio/src/index.module.css
packages/select/src/vars.css
packages/skeleton/src/index.module.css
packages/slider/src/index.module.css
packages/status/src/index.module.css
packages/switch/src/index.module.css
packages/tag/src/index.module.css
packages/themes/src/default.css
packages/themes/src/mixins/button/mobile.css
packages/themes/src/mixins/button/site-inverted.css
packages/themes/src/mixins/button/site.css
packages/themes/src/mixins/form-control/click.css
packages/themes/src/mixins/select/click.css
packages/toast-plate/src/index.module.css
packages/tooltip/src/index.module.css
packages/vars/src/border-radius.css

feat(vars): introducing border-radius vars

---

packages/themes/src/default.css

fix(themes): fixes border-radius

---

packages/button/src/index.module.css

Фиксит вертикальное выравнивание кнопок, если поставить несколько в ряд:

fix(button): fixed alignment of several buttons in a row

---

docs/7.gaps.stories.mdx
yarn.lock

Добавила `--gap-3xs` в табличку с описанием переменных.
Может, еще и про переменные `*-neg` добавить описание? А то, если не залезать в исходники, то и не узнать про наличие этих переменных.

fix(gaps): add description

---

packages/tabs/src/Component.stories.mdx

chore(tabs): improve docs

---

packages/utils/helpers.ts
packages/utils/screenshot-testing.ts

Возможность указать тему для скриншот тестов

chore: allow to test themes

---

packages/tabs/src/components/tab/Component.tsx
packages/tabs/src/components/tabs/Component.test.tsx
packages/tabs/src/typings.ts

fix(tabs): optional children

---

packages/checkbox/src/index.module.css
packages/themes/src/mixins/checkbox/click.css

Актуализируем стили чекбокса
[ЦАРЬ-МАКЕТ](https://www.figma.com/file/HamKNQwRq5qQUbDde6YSml/%F0%9F%9B%A0%D0%9A%D0%BE%D0%BD%D1%82%D1%80%D0%BE%D0%BB%D1%8B-%D0%BD%D0%B0-%D0%B2%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82%D0%B0%D1%85?node-id=10%3A62646)
1. Добавлен отступ по 2px вокруг кружка
2. *Актуализированы цвета*

refactor(checkbox): styles update

---

packages/calendar-input/src/Component.stories.mdx
packages/calendar-input/src/index.module.css
packages/calendar-input/src/stories.module.css

Инпут может быть меньше ширины календаря

feat(calendar-input): remove input width

---

packages/mq/src/mq.json

Добавил mobile-xs = 320
**BREAKING CHANGE**: mobile-s теперь 360

feat(mq): change mobile-s to mobile-xs

---

packages/amount-input/src/Component.test.tsx
packages/amount-input/src/utils/index.ts

Неправильное значение в payload value в компоненте AmountInput
Ввести в компоненте AmountInput значение 1,1
В минорных единицах должно быть 110
- OS: MacOS
- Version: 10
- OS: iOS 10
- Version: 65

fix(amount-input): fix float in amount input

---

packages/space/src/Component.stories.mdx
packages/space/src/Component.tsx

Не добавляется data-test-id для компонента Space :C

fix(space): fix dataTestId

---

packages/skeleton/src/index.module.css

fix(skeleton): remove extra bottom margin

---

package.json
yarn.lock

fix #552 
Обновил наш форк и открыл [issue](https://github.com/egoist/rollup-plugin-postcss/issues/366) в основную репу

fix: update plugin

---

packages/calendar-input/src/Component.tsx
packages/calendar/src/components/header/index.module.css
packages/calendar/src/useCalendar.ts

- В IE закрывался календарь при выборе другого года или месяца
- Поправил проблемы с фокусом в IE
- Поправил позицию стрелок в IE

fix(calendar): ie fixes

---

packages/backdrop/src/index.module.css
packages/backdrop/src/vars.css
packages/drawer/src/Component.tsx
packages/drawer/src/index.module.css

fix(drawer): lost vars

---

packages/dropzone/package.json
packages/dropzone/src/Component.stories.mdx
packages/dropzone/src/Component.test.tsx
packages/dropzone/src/Component.tsx
packages/dropzone/src/__image_snapshots__/dropzone-main-props-error-0-overlay-visible-0-snap.png
packages/dropzone/src/__image_snapshots__/dropzone-main-props-error-0-overlay-visible-1-snap.png
packages/dropzone/src/__image_snapshots__/dropzone-main-props-error-1-overlay-visible-0-snap.png
packages/dropzone/src/__image_snapshots__/dropzone-main-props-error-1-overlay-visible-1-snap.png
packages/dropzone/src/__snapshots__/Component.test.tsx.snap
packages/dropzone/src/component.screenshots.test.tsx
packages/dropzone/src/index.module.css
packages/dropzone/src/index.ts
packages/dropzone/src/utils.ts
packages/dropzone/tsconfig.json
yarn.lock

[Макет](https://www.figma.com/file/uGndMZufgvqxaNQTaNTEjG/B2B-Web-Components?node-id=13855%3A101731)

feat(dropzone): add component

---

packages/file-upload-item/package.json
packages/file-upload-item/src/Component.stories.mdx
packages/file-upload-item/src/Component.test.tsx
packages/file-upload-item/src/Component.tsx
packages/file-upload-item/src/__image_snapshots__/name-photo-jpg-upload-date-22-01-2018-size-45000-download-link-link-upload-status-success-show-delete-true-1-snap.png
packages/file-upload-item/src/__image_snapshots__/name-photo-jpg-upload-date-22-01-2018-size-45000-show-delete-true-upload-status-error-1-snap.png
packages/file-upload-item/src/__image_snapshots__/name-photo-jpg-upload-date-22-01-2018-size-45000-show-delete-true-upload-status-loading-1-snap.png
packages/file-upload-item/src/__image_snapshots__/name-photo-jpg-upload-date-22-01-2018-size-45000-show-delete-true-upload-status-uploading-1-snap.png
packages/file-upload-item/src/__image_snapshots__/name-photo-jpg-upload-date-22-01-2018-size-45000-show-restore-true-1-snap.png
packages/file-upload-item/src/__image_snapshots__/name-photo-jpg-upload-status-error-show-delete-true-1-snap.png
packages/file-upload-item/src/__image_snapshots__/name-photo-jpg-upload-status-loading-show-delete-true-1-snap.png
packages/file-upload-item/src/__image_snapshots__/name-photo-jpg-upload-status-success-show-delete-true-1-snap.png
packages/file-upload-item/src/__image_snapshots__/name-photo-jpg-upload-status-uploading-show-delete-true-1-snap.png
packages/file-upload-item/src/__snapshots__/Component.test.tsx.snap
packages/file-upload-item/src/component.screenshots.test.tsx
packages/file-upload-item/src/index.module.css
packages/file-upload-item/src/index.ts
packages/file-upload-item/src/utils.test.ts
packages/file-upload-item/src/utils.ts
packages/file-upload-item/tsconfig.json

[Макет](https://www.figma.com/file/uGndMZufgvqxaNQTaNTEjG/B2B-Web-Components?node-id=9591%3A75058)
[Arui-private](https://digital.alfabank.ru/demo/arui-private/#/Components/FileUploadItem)

feat(file-upload-item): add component

---

packages/modal/src/Component.desktop.tsx
packages/modal/src/Component.stories.mdx

Дизайнеры хотят, чтобы можно было фиксировать модалку, если высота содержимого меняется

feat(modal): fixed position

---

packages/select/src/components/field/Component.tsx
packages/select/src/components/field/index.module.css

немного меняем поведение селекта

feat(select): label + placeholder

---

packages/notification/src/Component.tsx

Вынес полифилл для element.closest в onmount

fix(notification): move closest polyfill to mount

---

packages/calendar-input/package.json
packages/toast/package.json
packages/tooltip/package.json

fix: update popover versions

---

packages/select/package.json
packages/select/src/Component.stories.mdx
packages/select/src/components/base-select/Component.tsx

Пересчитываем ширину выпадающего списка, когда селект открыт
https://monosnap.com/file/GQqSKr33N4vxQMeR2jwl39JUWxlI4m
https://monosnap.com/file/tz207e97tf3joSU2YqSQgjqp3cMNtl

fix(select): recalc options-list width when open

---

packages/drawer/src/Component.tsx
packages/drawer/src/__snapshots__/Component.test.tsx.snap
packages/drawer/src/index.module.css

PDS-221
https://cloud.protopie.io/p/e7ba2888ff

feat(drawer): update animtaion

---

packages/screenshot-utils/screenshots-story/sprite.stories.tsx
packages/screenshot-utils/utils.ts
packages/select/src/__image_snapshots__/select-placeholder-label-snap.png
packages/select/src/component.screenshots.test.tsx
packages/select/src/components/field/Component.tsx

#535 немного поломал отображение block={false} селекта без плейсхолдера 
Пофиксил

fix(select): fix hidden label

---

packages/input/src/Component.stories.mdx
packages/input/src/Component.tsx
packages/input/src/index.module.css

Сделал нормальный автофилл для инпута
https://monosnap.com/file/cm6RivkvtEiShfgUP9fNjpO42xdf1t
https://monosnap.com/file/0Ql48IKmCfbZPnqWv9vGGmMIwgTUq7

feat(input): pretty webkit autofill

---

packages/select/src/Component.test.tsx
packages/select/src/components/base-select/Component.tsx

fix(select): add aria-disabled when disabled

---

packages/modal/src/components/footer/index.module.css
packages/modal/src/vars.css
packages/themes/src/mixins/modal/click.css

Стики футер в теме клика должен  всегда оставаться серым. Даже когда доезжает до нижней границы.

fix(modal): click theme sticky footer bg

---

packages/collapse/src/Component.stories.mdx
packages/collapse/src/Component.test.tsx
packages/collapse/src/Component.tsx
packages/collapse/src/__snapshots__/Component.test.tsx.snap
packages/collapse/src/index.module.css

добавил возможность управлять состоянием компонента снаружи

feat(collapse): add ability to change state using prop expanded

---

packages/base-modal/src/Component.tsx
packages/base-modal/src/index.module.css
packages/drawer/src/index.module.css
packages/modal/src/desktop.module.css
packages/modal/src/mobile.module.css

1. Фикс стилей в IE
2. Фикс фуллскрина в safari 13

fix(modal): fix styles

---

.storybook/blocks/css-vars/css-vars.tsx
packages/button/src/docs/component.stories.mdx

Теперь переменные у кнопки распределены на 3 файла. Обновил доку.
Переменные для inverted не будем показывать? Кажется, что визуально сильно раздует.

docs(button): updates docs

---

packages/base-modal/src/Component.tsx
packages/base-modal/src/utils.ts
packages/bottom-sheet/package.json
packages/bottom-sheet/src/__snapshots__/component.test.tsx.snap
packages/bottom-sheet/src/component.test.tsx
packages/bottom-sheet/src/component.tsx
packages/bottom-sheet/src/components/footer/Component.tsx
packages/bottom-sheet/src/components/footer/index.module.css
packages/bottom-sheet/src/components/swipeable-backdrop/Component.tsx
packages/bottom-sheet/src/index.module.css
packages/bottom-sheet/tsconfig.json

Перевел BottomSheet на BaseModal

refactor(bottom-sheet): migrate to base modal

---

packages/base-modal/src/Component.test.tsx
packages/base-modal/src/Component.tsx

Восстанавливаем стили body не только при exited, но и при unmount

fix(base-modal): restore body styles on unmount

---

packages/themes/src/mixins/select/click.css

Отступ между галкой и контентом 0
Отркрыть демку с селектом
Отступ между галкой и контентом 16px
- OS: MacOS
- Version: 10
- OS: iOS 10
- Version: 65

fix(select): fix checkmark

---

packages/select/src/components/base-select/Component.tsx

Немного переделал работу с resizeObserver, т.к. он не учитывал смену optionsListWidth

fix(select): optionsListWidth prop

---

packages/icon-button/src/index.module.css

Поправил опечатку в названии переменной

fix(icon-button): fix typo in css variable

---

packages/plate/src/Component.test.tsx
packages/plate/src/Component.tsx
packages/plate/src/docs/component.stories.mdx
packages/plate/src/docs/description.mdx
packages/plate/src/index.module.css
packages/toast/src/component.test.tsx
packages/toast/src/component.tsx
packages/toast/src/docs/component.stories.mdx
packages/toast/src/docs/description.mdx

- `Plate`: Добавил переменные для бордера
- `Plate`: Добавил пропсу `open` для управления видимостью
- `Toast`: Добавил возможность рендерить в качестве плашки любой компонент (например, Plate)

feat(plate): update vars

---

packages/typography/src/text/component.tsx
packages/typography/src/title/component.tsx

Добавил `restProps` в типографику

feat(typography): add rest props

---

packages/tooltip/src/Component.stories.mdx
packages/tooltip/src/Component.test.tsx
packages/tooltip/src/Component.tsx
packages/tooltip/src/__image_snapshots__/tooltip-test-hint-view-snap.png
packages/tooltip/src/__snapshots__/Component.test.tsx.snap
packages/tooltip/src/component.screenshots.test.tsx
packages/tooltip/src/index.module.css

Добавлен вид Hint
https://www.figma.com/file/uGndMZufgvqxaNQTaNTEjG/B2B-Web-Components?node-id=21177%3A21

feat(tooltip): add hint view

---

packages/picker-button/src/__snapshots__/Component.test.tsx.snap
packages/select/src/components/option/Component.tsx
packages/select/src/components/option/index.module.css

Если в айтеме много текста то он размазывается по всей высоте. В макете есть отступы.
1. Перейти на страницу '...'
2. Нажать на кнопку '...'
- OS: MacOS
- Version: 10
- OS: iOS 10
- Version: 65

fix(select): fix top bottom paddings

---

packages/select/src/__image_snapshots__/select-interactions-tests-click-open-select-select-one-item-4-snap.png
packages/select/src/__image_snapshots__/select-optgroup-click-snap.png
packages/select/src/__image_snapshots__/select-optgroup-default-snap.png
packages/select/src/vars.css

Не тот цвет в заголовке optgroup компонента select

style(select): change optgroup label color

---

packages/notification/src/Component.tsx

Добавлена возможность создать закрепленную нотификацию (которая не закрывается по таймауту, закрываемую только по нажатию крестика)

feat(notification): add null autoCloseDelay

---

.storybook/preview.js

Сортирует все истории по алфавиту

feat(storybook): sort stories by alphabet

---

packages/dark-theme-styles-injector/src/component.tsx

Заметил косяк, доп. стили, прокидываемые в компонент, неправильно рендерились

fix(dark-theme-styles-injector): fix rendering passed styles

---

packages/calendar/src/Component.test.tsx
packages/calendar/src/Component.tsx
packages/calendar/src/components/select-button/Component.tsx
packages/calendar/src/components/select-button/index.module.css

fix(calendar): fix select-button disabled+selected state

---

packages/picker-button/src/__image_snapshots__/picker-button-test-positioning-2-snap.png
packages/picker-button/src/__image_snapshots__/picker-button-test-positioning-3-snap.png
packages/picker-button/src/__image_snapshots__/picker-button-test-positioning-snap.png
packages/picker-button/src/__snapshots__/Component.test.tsx.snap
packages/select/src/Component.test.tsx
packages/select/src/__image_snapshots__/select-interactions-tests-click-open-select-select-one-item-2-snap.png
packages/select/src/__image_snapshots__/select-interactions-tests-default-open-select-select-one-item-2-snap.png
packages/select/src/__image_snapshots__/select-interactions-tests-long-options-snap.png
packages/select/src/__image_snapshots__/select-interactions-tests-visible-options-snap.png
packages/select/src/__image_snapshots__/select-optgroup-click-snap.png
packages/select/src/__image_snapshots__/select-optgroup-default-snap.png
packages/select/src/components/base-select/Component.tsx

Не подсвечиваем первый пункт при открытии, т.к. это вызывает проблемы в некоторых кейсах. 
Да и нативный селект тоже не подсвечивает

feat(select): dont highlight first option on open

---

packages/themes/src/mixins/confirmation/mobile.css
packages/themes/src/mixins/mobile.css

Для мобилок нужна другая типографика

feat(themes): confirmation mobile theme

---

packages/badge/src/Component.tsx
packages/badge/src/__image_snapshots__/badge-screenshots-view-icon-view-0-visible-icon-outline-0-icon-color-6-snap.png
packages/badge/src/__image_snapshots__/badge-screenshots-view-icon-view-0-visible-icon-outline-1-icon-color-6-snap.png
packages/badge/src/component.screenshots.test.tsx
packages/badge/src/docs/Component.stories.mdx
packages/badge/src/index.module.css

добавлен новый цвет иконки в badge

feat(badge): add icon color

---

packages/alert/src/index.module.css
packages/vars/src/border-radius.css

feat(vars): add border-radius-xs

---

packages/phone-input/src/Component.tsx
packages/phone-input/src/docs/Component.stories.mdx
packages/phone-input/src/utils/index.ts

feat(phone-input): add 'clearableCountyCode' prop

---

packages/select/src/Component.test.tsx
packages/select/src/components/base-select/Component.tsx
packages/select/src/components/options-list/Component.tsx
packages/select/src/components/virtual-options-list/Component.tsx
packages/select/src/typings.ts

Добавляем обработчик скролла в селект

feat(select): add scroll handler

---

packages/phone-input/src/Component.test.tsx
packages/phone-input/src/Component.tsx
packages/phone-input/src/docs/Component.stories.mdx

Исправляет передачу value в инпут

fix(phone-input): value prop

---

packages/list/src/docs/description.mdx

chore(list): add webview snippet (PDS-245)

---

packages/tooltip/src/Component.tsx

Пофиксил [баг](https://alfamobile.slack.com/archives/CQAPZQUJG/p1626705055129500?thread_ts=1626686368.128400&cid=CQAPZQUJG)

fix(tooltip): fix bug with controlled state

---

packages/attach/src/Component.test.tsx
packages/attach/src/Component.tsx
packages/attach/src/docs/Component.stories.mdx

#743
К сожалению, можно только симулировать контролируемое поведение
https://ru.reactjs.org/docs/uncontrolled-components.html

feat(attach): simulate controlled state

---

packages/date-input/package.json
packages/date-input/src/Component.test.tsx
packages/date-input/src/Component.tsx
packages/date-input/src/__snapshots__/Component.test.tsx.snap
packages/date-input/src/docs/Component.stories.mdx
packages/date-input/src/docs/description.mdx
packages/date-input/src/index.module.css
packages/date-input/src/index.ts
packages/date-input/src/utils/date-correction-pipe.ts
packages/date-input/src/utils/format.ts
packages/date-input/src/utils/index.ts
packages/date-input/src/utils/native-supports.ts
packages/date-input/tsconfig.json
packages/masked-input/src/Component.tsx

feat(date-input): add component

---

packages/calendar-input/src/Component.tsx
packages/calendar-input/src/__image_snapshots__/calendar-input-interactions-tests-open-calendar-snap.png
packages/calendar-input/src/__snapshots__/Component.test.tsx.snap
packages/calendar-input/src/index.module.css
packages/calendar-range/src/__snapshots__/Component.test.tsx.snap
packages/date-input/src/Component.tsx
packages/date-input/src/__snapshots__/Component.test.tsx.snap
packages/date-input/src/index.module.css

DateInput оказывается без иконки

fix: move icon from date input to calendar input

---

packages/amount-input/src/index.module.css

Убрал переопределение цвета каретки

fix(amount-input): remove caret-color override

---

packages/dropzone/src/Component.tsx
packages/dropzone/src/index.module.css

Не показывается оверлэй при ховере дочерних элементов

fix(attach): fix drag counter & styles

---

packages/plate/src/index.module.css

Фиксит баг, когда Alert внутри Plate получает каскадом лишние стили

fix(plate): alert in plate cascade issue

---

packages/modal/src/desktop.module.css

пока так. Вообще надо бы наверное сначала менять размер модалки, а потом уже показывать мобильную

fix(modal): max-width 100%

---

packages/select/src/presets/useLazyLoading/hook.tsx

Небольшой фикс лейзилоада, когда не приходят новые итемы - не инкрементить значение офсета

fix(select): lazy loading select

---

packages/plate/src/Component.test.tsx
packages/plate/src/Component.tsx
packages/plate/src/index.module.css

Не сворачивает вкладку, если события произошли внутри контентной области

fix(plate): folding area

---

packages/plate/src/Component.test.tsx
packages/plate/src/Component.tsx
packages/plate/src/docs/description.mdx
packages/plate/src/index.module.css

С управлением folded было что-то не то.
- Предполагалось, что `open` будет управлять свернутостью, но это не работало. Заменил `open` на `folded`, теперь все ок. 
- Добавил коллбэк onToggle
- Добавил тесты и пример

refactor(plate): folded state

---

packages/confirmation/src/component.tsx
packages/confirmation/src/components/countdown/component.tsx
packages/confirmation/src/components/countdown/index.module.css
packages/confirmation/src/components/index.ts
packages/confirmation/src/components/sign-confirmation/component.tsx
packages/confirmation/src/docs/Component.stories.mdx
packages/confirmation/src/index.ts

Добавил возможность прокидывать кастомный контент в `Countdown`.
Изменил форматирование времени, чтобы отображались часы.
Предлагаю как можно скорее переписать этот компонент, так как внесение в него даже маленьких правок стало очень проблематично(

feat(confirmation): add custom countdown content, change time format

---

packages/icon-button/src/Component.test.tsx
packages/icon-button/src/Component.tsx
packages/icon-button/src/__snapshots__/Component.test.tsx.snap
packages/icon-button/src/docs/description.mdx

Хотел использовать href для IconButton, внутри пробрасываются restProps, но в типах не было
size и view переопределены, поэтому excluded, возможно стоит туда добавить leftAddons

feat(icon-button): Rest props for IconButton from Button

---

packages/pure-input/src/index.module.css
packages/textarea/src/default.module.css
packages/textarea/src/inverted.module.css

fix(textarea): missing vars

---

packages/bank-card/src/docs/Component.stories.mdx
packages/bank-card/src/index.module.css

fix(bank-card): improve docs, fix focus bg (PDS-281)

---

packages/themes/src/mixins/form-control/mobile.css
packages/themes/src/mixins/input/mobile.css

fix: wrong mobile colors

---

packages/password-input/src/__snapshots__/component.test.tsx.snap
packages/password-input/src/component.tsx
packages/password-input/src/docs/component.stories.mdx
packages/password-input/src/index.module.css

Добавляем rightAddons в PasswordInput

feat(password-input): show right addons (PDS-283)

---

packages/confirmation/src/components/code-input/index.module.css
packages/input/src/default.module.css
packages/input/src/inverted.module.css

[Фикс пунктов 2 и 3](https://alfamobile.slack.com/archives/C020JK1J2L8/p1630941214038400)

fix: confirmation & input

---

packages/popover/package.json
packages/popover/src/Component.tsx
packages/popover/src/docs/Component.stories.mdx
packages/popover/src/docs/description.mdx

feat(popover): add useAnchorWidth prop

---

packages/dropzone/src/Component.test.tsx
packages/dropzone/src/Component.tsx
packages/dropzone/src/__image_snapshots__/dropzone-main-props-error-0-overlay-visible-0-snap.png
packages/dropzone/src/__image_snapshots__/dropzone-main-props-error-0-overlay-visible-1-snap.png
packages/dropzone/src/__image_snapshots__/dropzone-main-props-error-1-overlay-visible-0-snap.png
packages/dropzone/src/__image_snapshots__/dropzone-main-props-error-1-overlay-visible-1-snap.png
packages/dropzone/src/components/index.ts
packages/dropzone/src/components/overlay/Component.tsx
packages/dropzone/src/components/overlay/index.module.css
packages/dropzone/src/components/overlay/index.ts
packages/dropzone/src/docs/Component.stories.mdx
packages/dropzone/src/docs/description.mdx
packages/dropzone/src/index.module.css
packages/themes/src/mixins/click.css
packages/themes/src/mixins/dropzone/click.css

— Добавили disabled
— Добавили возможность установить кастомный Overlay (или выключить его вообще)
— Добавили состояние наведения для клика
— Изменили бордер
Предлагаю обсудить различия между темой клика и всеми остальными и привести все к какому-то более-менее общему виду. Это касается бордера и курсора.
Курсор pointer не стал пока делать, т.к. внутри дропзоны может быть что угодно и должна быть четкая индикация, куда нужно нажимать.

feat(dropzone): design improvements (PDS-282)

---

packages/typography/src/text/component.tsx
packages/typography/src/title/component.tsx

feat(typography): add ref

---

packages/gallery/src/Component.tsx
packages/gallery/src/components/header/Component.tsx
packages/gallery/src/components/image-preview/index.module.css
packages/gallery/src/components/image-viewer/component.tsx
packages/gallery/src/components/image-viewer/index.module.css
packages/gallery/src/components/image-viewer/slide.tsx
packages/gallery/src/docs/description.mdx
packages/gallery/src/types.ts

- Добавил пропсу `canDownload`, чтобы изображение было нельзя скачивать, так как оказалось, что и такой кейс возможен.
- Пофиксил баг + немного отрефакторил

feat(gallery): add `canDownload` image prop, some refactoring

---

packages/confirmation/package.json
packages/confirmation/src/Component.test.tsx
packages/confirmation/src/__snapshots__/Component.test.tsx.snap
packages/confirmation/src/component.tsx
packages/confirmation/src/components/code-input/index.module.css
packages/confirmation/src/components/index.ts
packages/confirmation/src/components/overlimit/component.tsx
packages/confirmation/src/components/overlimit/index.module.css
packages/confirmation/src/components/overlimit/index.ts
packages/confirmation/src/docs/Component.stories.mdx
packages/confirmation/src/docs/description.mdx

Добавил новый вид ошибки с блокировкой ввода и скрытием инпута на время блокировки.
Примеры
- при ошибочно введенном проверочном коде несколько раз
- при превышении лимита на запрос кода и блокировки на некоторое время
PR для того чтобы завалидировать решение, если все ок то дальше уже добавлю тестов и больше примеров в доку

feat(confirmation): design update, new type of error "overlimit" and blocking input 

---

packages/intl-phone-input/src/__snapshots__/component.test.tsx.snap
packages/picker-button/src/__snapshots__/Component.test.tsx.snap
packages/select-with-tags/src/__snapshots__/component.test.tsx.snap
packages/select/src/Component.test.tsx
packages/select/src/__snapshots__/Component.test.tsx.snap
packages/select/src/components/base-select/Component.tsx
packages/select/src/docs/description.mdx
packages/select/src/presets/useLazyLoading/use-lazy-loading.test.tsx
packages/select/src/typings.ts

Добавил возможность управлять открытием селекта полностью снаружи

feat(select): controlled open

---

packages/file-upload-item/src/Component.tsx

сделал правильное описание пропса showRestore

fix(file-upload-item): fix description prop

---

package.json
yarn.lock

https://alfamobile.slack.com/archives/C020JK1J2L8/p1632406573085500

fix: bump react-popper

---

packages/input/src/default.module.css
packages/input/src/index.module.css
packages/input/src/inverted.module.css
packages/textarea/src/default.module.css
packages/textarea/src/index.module.css
packages/textarea/src/inverted.module.css

fix: input & textarea disabled color on safari

---

packages/calendar-range/src/useCalendarMonthes.ts

```tsx
<CalendarRange calendarPosition='popover' valueFrom="10.10.2021" valueTo="10.11.2021" />
```

fix(calendar-range): fix default month to

---

packages/slider-input/src/Component.test.tsx
packages/slider-input/src/Component.tsx

fix(slider-input): classnames overriding

---

packages/tabs/src/components/primary-tablist/Component.tsx
packages/tabs/src/components/primary-tablist/index.module.css
packages/tabs/src/components/scrollable-container/Component.tsx
packages/tabs/src/components/scrollable-container/index.module.css
packages/tabs/src/components/tabs/__snapshots__/Component.test.tsx.snap
packages/tabs/src/docs/description.mdx
packages/tabs/src/vars.css

fix(tabs): hide native scrollbar on scrollable tabs properly

---

packages/circular-progress-bar/src/Component.tsx
packages/circular-progress-bar/src/__image_snapshots__/circular-progress-bar-sprite-snap.png
packages/circular-progress-bar/src/component.screenshots.test.tsx
packages/circular-progress-bar/src/docs/Component.stories.mdx
packages/circular-progress-bar/src/index.module.css
packages/select/src/Component.test.tsx

https://www.figma.com/file/KlFOLLkKO8rtvvQE3RXuhq/Click-Library?node-id=11501%3A44531
(С тестом по селекту отдельно разберёмся)

feat(circular-progress-bar): new size S

---

packages/radio/src/Component.test.tsx
packages/radio/src/Component.tsx
packages/radio/src/__snapshots__/Component.test.tsx.snap

Добавил условный рендеринг для контейнера label и hint

fix(radio): add condition rendering to label & hint container

---

packages/themes/src/mixins/dropzone/click.css

http://jira.moscow.alfaintra.net/browse/PDS-306

fix(dropzone): remove dropzone-active-bg for click theme

---

packages/calendar-input/src/Component.test.tsx
packages/calendar-input/src/Component.tsx
packages/calendar-input/src/__snapshots__/Component.test.tsx.snap

fix #876 
— добавил вызов onKeyDown
— убрал явную установку inputClassName

fix(calendar-input): render rightAddons, add missing overrides

---

packages/bank-card/src/index.module.css

fix(bank-card): fix use-photo icon color

---

packages/plate/src/Component.tsx
packages/plate/src/index.module.css

ставим pointer курсор только если foldable={true}

fix(plate): cursor pointer only for foldable plates

---

.storybook/public/global.css
docs/1.getting-started.stories.mdx
docs/6.typography.stories.mdx
docs/8.icons.stories.mdx
packages/calendar/src/vars.css
packages/cdn-icon/src/Component.tsx
packages/gallery/src/vars.css
packages/input/src/default.module.css
packages/input/src/inverted.module.css
packages/modal/src/vars.css
packages/plate/src/index.module.css
packages/screenshot-utils/helpers.ts
packages/themes/src/mixins/calendar/click.css
packages/themes/src/mixins/input/site.css
packages/themes/src/mixins/modal/click.css
packages/themes/src/mixins/select/click.css

fix: use new cdn

---

.storybook/public/global.css
docs/1.getting-started.stories.mdx
docs/6.typography.stories.mdx
docs/8.icons.stories.mdx
packages/calendar/src/vars.css
packages/cdn-icon/src/Component.tsx
packages/gallery/src/vars.css
packages/input/src/default.module.css
packages/input/src/inverted.module.css
packages/modal/src/vars.css
packages/plate/src/index.module.css
packages/screenshot-utils/helpers.ts
packages/themes/src/mixins/calendar/click.css
packages/themes/src/mixins/input/site.css
packages/themes/src/mixins/modal/click.css
packages/themes/src/mixins/select/click.css

Revert "fix: новый cdn иконок (#913)"

---

.storybook/public/global.css
docs/1.getting-started.stories.mdx
docs/6.typography.stories.mdx
docs/8.icons.stories.mdx
packages/calendar/src/vars.css
packages/cdn-icon/src/Component.tsx
packages/gallery/src/vars.css
packages/input/src/default.module.css
packages/input/src/inverted.module.css
packages/modal/src/vars.css
packages/plate/src/index.module.css
packages/screenshot-utils/helpers.ts
packages/themes/src/mixins/calendar/click.css
packages/themes/src/mixins/input/site.css
packages/themes/src/mixins/modal/click.css
packages/themes/src/mixins/select/click.css

BREAKING CHANGE: Добавьте новый домен в список разрешенных 'img-src': `'self' alfabank.gcdn.co data: 'self'`

fix!: новый cdn иконок (#913)

---

packages/picker-button/src/__snapshots__/Component.test.tsx.snap
packages/picker-button/src/field/Component.tsx
packages/select/src/docs/description.mdx

#914
В компоненте PickerButton обернул Field в div, и прокинул в него ref.
В компоненте Select добавил описание использования Button для каcтомного Field

fix(picker-button): Сдвигающийся Popover в PickerButton / Select

---

packages/checkbox-group/src/index.module.css
packages/themes/src/mixins/checkbox-group/click.css
packages/themes/src/mixins/click.css

feat(checkbox-group): add click theme

---

packages/select-with-tags/src/components/tag/index.module.css
packages/stepped-progress-bar/src/components/step-bar/index.module.css

Добавил забытые импорты переменных

fix: add missing vars imports

---

packages/button/src/index.module.css
packages/tooltip/src/Component.tsx
packages/tooltip/src/__snapshots__/Component.test.tsx.snap
packages/tooltip/src/component.responsive.tsx
packages/tooltip/src/index.module.css
packages/tooltip/src/responsive.module.css

#799 
Добавил pointer-events: none для контента disabled кнопки.
Обернул  дочерний компонент Тултипа span-ом и добавил disabled классы

fix(button): fix disabled button & tooltip

---

packages/input/src/Component.tsx
packages/input/src/__image_snapshots__/input-clear-icon-default-theme-2-snap.png
packages/input/src/default.module.css
packages/input/src/index.module.css
packages/input/src/inverted.module.css

http://jira.moscow.alfaintra.net/browse/PDS-323

fix(input): use icon for clear button instead background

---

packages/button/src/index.module.css

fix(button): remove unnecessary padding for view ghost

---

packages/amount-input/src/Component.test.tsx
packages/amount-input/src/Component.tsx
packages/amount-input/src/__snapshots__/Component.test.tsx.snap
packages/slider-input/src/docs/description.mdx

fix(amount-input): dont render 0 for empty value, allow string as value

---

packages/dropzone/src/Component.tsx

fix(dropzone): reset dragCounter on drop anyway

---

packages/table/src/components/texpandable-row/index.module.css

Не заметили косячок с высотой раскрывающейся ячейки

fix(table): fix expandable row cell height

---

packages/vars/src/colors-addons.css
tools/color-mods.json

fix(vars): remove unused colors

---

packages/base-modal/package.json
packages/base-modal/src/utils.ts
packages/base-modal/tsconfig.json
packages/global-store/package.json
packages/global-store/src/GlobalStore.ts
packages/global-store/src/ModalStore.ts
packages/global-store/src/index.ts
packages/global-store/tsconfig.json
typings/global.d.ts
yarn.lock

Попробовал вынести стор модалки в глобальный объект

feat(base-modal): extract modal store to global

---

packages/table/src/components/thead-cell/index.module.css

неправильный отступ у заголовков

fix(table): fix th paddings

---

packages/cdn-icon/src/Component.test.tsx
packages/cdn-icon/src/Component.tsx

Не было возможности стилизовать компонент CDNIcon

add className prop to cdn-icon

---

.storybook/addons/theme-switcher/register.js
.storybook/addons/theme-switcher/themes/intranet.css
.storybook/addons/theme-switcher/utils.js
bin/build-themes.js
packages/button/src/__image_snapshots__/button-inverted-views-themes-intranet-theme-snap.png
packages/button/src/__image_snapshots__/button-views-themes-intranet-theme-snap.png
packages/button/src/component.screenshots.test.tsx
packages/custom-button/src/__image_snapshots__/custom-button-colors-disabled-state-and-themes-intranet-theme-snap.png
packages/custom-button/src/component.screenshots.test.tsx
packages/themes/src/mixins/button/intranet.css
packages/themes/src/mixins/checkbox/intranet.css
packages/themes/src/mixins/confirmation/intranet.css
packages/themes/src/mixins/form-control/intranet.css
packages/themes/src/mixins/input/intranet.css
packages/themes/src/mixins/intranet.css
packages/themes/src/mixins/mobile.css
packages/themes/src/mixins/radio/intranet.css
packages/themes/src/mixins/slider-input/intranet.css
packages/themes/src/mixins/slider/intranet.css
packages/themes/src/mixins/tag/intranet.css

feat(themes): introducing intranet theme

---

packages/button/src/Component.tsx
packages/codemod/README.md

Забыли указать воркспейс в примерах.

doc: Исправить документацию по запуску кодмодов.

---

packages/notification/src/Component.tsx

feat(notification): disabled trackMouse

---

package.json
packages/vars/src/typography.css
yarn.lock

Миксины для новых текстовых стилей

feat(vars): updated typography

---

packages/calendar-input/src/index.module.css
packages/themes/src/mixins/calendar-input/intranet.css
packages/themes/src/mixins/calendar-input/mobile.css
packages/themes/src/mixins/intranet.css
packages/themes/src/mixins/mobile.css

fix(calendar-input): styles

---

packages/attach/src/__image_snapshots__/attach-interactions-tests-attach-file-snap.png
packages/progress-bar/src/Component.test.tsx
packages/progress-bar/src/Component.tsx
packages/progress-bar/src/__image_snapshots__/progress-bar-main-props-sprite-snap.png
packages/progress-bar/src/__snapshots__/Component.test.tsx.snap
packages/progress-bar/src/component.screenshots.test.tsx
packages/progress-bar/src/docs/Component.stories.mdx
packages/progress-bar/src/index.module.css

http://jira.moscow.alfaintra.net/browse/PDS-316

feat(progress-bar): add size prop, additional views, new bg color

---

packages/themes/src/mixins/select/corp.css

замена тени выпадашки в corp теме

fix(select): change corp shadow

---

packages/calendar-range/src/hooks.ts
packages/calendar-range/src/views/static.tsx

fix(calendar-range): correct highlights

---

.storybook/blocks/component-header/ComponentHeader.tsx
docs/1.getting-started.stories.mdx
docs/2.theming.stories.mdx
docs/3.development-faq.stories.mdx
docs/4.statuses.stories.mdx
docs/5.colors.stories.mdx
docs/6.typography.stories.mdx
docs/7.gaps.stories.mdx
docs/8.icons.stories.mdx
docs/9.0.accessibility.stories.mdx
docs/9.1.images.stories.mdx
docs/9.2.video-audio.stories.mdx
docs/9.3.forms.stories.mdx
docs/9.4.tables.stories.mdx
docs/9.5.menu.stories.mdx
docs/9.6.keyboard.stories.mdx
docs/9.7.testing.stories.mdx

Заменил: `import { Title } from '@storybook/addon-docs/blocks';` -> `import { Title } from '@storybook/addon-docs';`
Добавил импорт `Meta` в сторях.
Удалил неиспользуемые импорты.

feat: Исправить импорты в сторях.

---

packages/base-modal/src/Component.tsx

Столкнулся с тем, что надо подписаться на скролл в сайд панеле, и не нашел такой возможности, может как-то по другому есть уже возможность?

feat(base-modal): add component ref for base modal

---

packages/typography/src/title-responsive/index.module.css

1) Изменен брейкпоинт мобильной типографики
Было: от 640px до 1024px
Стало: от 320px до 1024px
2) Поправлены стили мобильной типографики

fix(typography): changed styrene font styles for title responsive

---

.storybook/scope.ts
package.json
packages/bank-card/package.json
packages/calendar/package.json
packages/checkbox/package.json
packages/confirmation/package.json
packages/dropzone/package.json
packages/file-upload-item/package.json
packages/gallery/package.json
packages/input/package.json
packages/password-input/package.json
packages/picker-button/package.json
packages/select-with-tags/package.json
packages/toast-plate/package.json
yarn.lock

обновил иконки до актуальной версии

fix: update glyph deps

---

packages/picker-button/src/Component.tsx
packages/picker-button/src/__snapshots__/Component.test.tsx.snap
packages/picker-button/src/option/Component.tsx
packages/picker-button/src/option/index.module.css
packages/picker-button/src/option/index.ts
packages/picker-button/src/utils/index.ts
packages/select/src/components/option/Component.tsx
packages/select/src/components/option/index.module.css

плохо посмотрели пр в пикер(
- удалил иконку из селекта (потом добавим полноценно, если нужно)
- вернул стили в option
- перенес все в пикер
- обновил снэпшоты

fix: move icon from select to picker-button

---

packages/circular-progress-bar/src/Component.test.tsx
packages/circular-progress-bar/src/Component.tsx
packages/circular-progress-bar/src/__snapshots__/Component.test.tsx.snap

http://jira.moscow.alfaintra.net/browse/PDS-382

feat(circular-progress-bar): ReactNode as title or subtitle

---

packages/intl-phone-input/src/__snapshots__/component.test.tsx.snap
packages/intl-phone-input/src/component.tsx
packages/intl-phone-input/src/components/flag-icon/component.tsx
packages/intl-phone-input/src/components/flag-icon/index.module.css
packages/intl-phone-input/src/components/select-field/component.tsx
packages/intl-phone-input/src/components/select-field/index.module.css
packages/intl-phone-input/src/components/select/component.tsx

— чуть обновил стили, уменьшил отступы. Теперь на мобилке все будет влезать
— заюзал VirtualOptionsList, чтобы список рисовался и открывался быстрее 
close #1027

fix(intl-phone-input): design fixes

---

packages/tooltip/src/Component.test.tsx
packages/tooltip/src/Component.tsx

При нажатии на кнопку 'создать отчет' ничего не происходит
1. Перейти на страницу '...'
2. Нажать на кнопку '...'
При нажатии на кнопку должно появится модальное окно
- OS: MacOS
- Version: 10
- OS: iOS 10
- Version: 65

feat(tooltip): added anchor props

---

packages/attach/src/Component.tsx

fix(attach): always clear input

---

packages/list/src/docs/description.mdx
packages/list/src/index.ts
packages/list/src/presets.ts
packages/typography/src/index.ts
packages/typography/src/presets.ts

Необходимы пресеты для компонента List и Typography для отображения списка в webview
не изменился

feat(list): added list & typography presets
