alfa-laboratory/core-components

babel.config.js
Фейлится сборка пакета. Выводится след. ошибка:
```
Error: Babel was run with rootMode:"upward" but a root could not be found when searching upward from "/Users/alexyatsenko/projects/core-components/packages/button".
One of the following config files must be in the directory tree: "babel.config.js, babel.config.cjs, babel.config.mjs, babel.config.json".
```
Запустить `yarn build`
Пакет должен собираться.
Вернул конфиг babel'а, который был удален [тут](https://github.com/alfa-laboratory/core-components/commit/3bd5492bba179083cb26aa99c295a43f8e3be037#diff-fc10a6682269c1fefc2abe05d1500b8a)
=> fix(*): restore babel config

.github/workflows/main.yml, bin/demo-build.js
Теперь ссылка на сторибук публикуется автоматически после пуша.
- ссылка на сторибук после сборки сохраняется в `steps.demo_build.outputs.storybook_url`
- скрипт ищет открытый PR
- если PR есть, то бот оставляет коммент с ссылкой на демку
=> feat(*): post storybook url to PR after push

.github/CODEOWNERS
https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners
=> introducing codeowners

bin/build-root-package.sh
build-root-package.sh некорректно обрабатывает пакеты с дефисами в названии папки.
1. Назвать папку с пакетом через дефис. Например `pure-input`
2. Запустить `yarn build`
3. В папке `/dist` появится папка `pure`
Папка должна называться `pure-input`
=> fix(build-root-package): several hyphens in dir name

src/button/src/Component.stories.tsx, src/button/src/Component.tsx, src/input/src/Component.stories.tsx, src/input/src/Component.tsx, src/pure-input/src/Component.stories.tsx, src/pure-input/src/Component.tsx
Предложение отказаться от использования нативных атрибутов не по назначению.
Поэтому `htmlType` теперь просто `type`.
У кнопки `type: 'primary' | 'secondary' | 'outlined' | 'link' | 'ghost'` переименован во `view`.
Название `view` приехало из фижера и должно быть привычным для всех. 
Также рассматривали следующие варианты вместо `view`:
- type (ant)
- kind (akit/ibm)
- appearance (atlassian)
- variant (material)
=> refactor(*): replace type --> view. htmlType --> type.

.storybook/webpack.config.js
Сейчас в документацию компонента в storybook попадают только пользовательские пропсы.
Пример:
```typescript
type ButtonProps = ButtonHTMLAttributes<HTMLButtonElement> & {
/** Слот слева */
leftAddons?: React.ReactNode;
}
```
В storybook попадет один пропс: `leftAddons?: React.ReactNode`.
Хочется видеть в документации какие-то нативные пропсы тоже. По-этому предлагаю чем-то их помечать, например `(native prop)`:
```typescript
type ButtonProps = ButtonHTMLAttributes<HTMLButtonElement> & {
/** Слот слева */
leftAddons?: React.ReactNode;
/** Обработчик клика (native prop) */
onClick: ButtonHTMLAttributes<HTMLButtonElement>['onChange'];
}
```
=> Документация типов пропсов в storybook

src/portal/package.json, src/portal/src/Component.stories.tsx, src/portal/src/Component.test.tsx, src/portal/src/Component.tsx, src/portal/src/index.ts, src/portal/src/portalContainer.ts, src/portal/tsconfig.json
При создании компонента `Tooltip`, потребовался компонент `Portal`.
В реализации было учтено требование от сайта, что должен быть единый контейнер, куда будут рендериться childs.
При желании можно переопределить эту логику пропсой `getPortalContainer`
| Свойство     |                               Описание                                |       Тип       | Значение по умолчанию | Обязательное |
|--------------|:---------------------------------------------------------------------:|:---------------:|:---------------------:|-------------:|
| children|Дочерние элементы | ReactNode | -|     нет |
| getPortalContainer|Функция, возвращающая контейнер, в который будут рендериться дочерние элементы | () => Element | см. в коде |     нет |
=> Новый компонент Portal

packages/tag/src/index.module.css
При задизейбленном состоянии при наведении и нажатии на тэг были некорректные стили.
Это воспроизводилось, если поместить тэг внутрь тэга `<label />`
=> fix(tag): fix disabled state

packages/input/src/Component.stories.tsx, packages/input/src/Component.tsx
В **uncontrolled** инпуте лейбл наезжает на текст.
1. Перейти [сюда](https://alfa-laboratory.github.io/core-components/e2914b5691666e2a6e7de043ac65a1ec20ed3517/?path=/story/%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B-input--%D0%BF%D0%B5%D1%81%D0%BE%D1%87%D0%BD%D0%B8%D1%86%D0%B0)
2. Добавить инпуту лейбл
3. Ввести значение и убрать фокус
Сейчас состояние `filled` определяется по `value`. В случае uncontrolled инпута - этого пропса нет.
Пришлось добавить обработчик ввода и стейт `filled`.
=> fix(input): fix wrong filled state

.yarnrc, README.md, bin/publish.sh, commitlint.config.js, lerna.json, package.json, yarn.lock
Добавил линтинг коммитов:
[commitlint](https://github.com/conventional-changelog/commitlint)
[commitlint-lerna-scopes](https://github.com/conventional-changelog/commitlint/tree/master/@commitlint/config-lerna-scopes)
Коммиты можно делать с помощью утилиты `commitizen`:
```bash
$ git add .
$ yarn cm # запустит утилиту commitizen для создания коммита
$ git push
```
добавил скрипты в `package.json`:
`pub:patch`, `pub:minor`, `pub:major`
```bash
$ yarn pub:patch # соберет и выпустит patch-версию
$ yarn pub:minor # соберет и выпустит minor-версию
$ yarn pub:major # соберет и выпустит major-версию
```
Зафиксировал изменения в `README.MD`
`CHANGELOG.MD` начнет формироваться с последующим релизом
=> Линтинг коммитов, генерация CHANGELOG.MD

packages/popover/src/Component.tsx
Позволяет устанавливать отдельные transition-пропсы.
=> fix(core-components-popover): make transition props optional

packages/popover/src/index.module.css
Изменил box-sizing на border-box, чтобы можно было поставить поповеру ширину родителя (width=100%) и бордер не торчал наружу.
=> fix(core-components-popover): change box-sizing to border-box

packages/popover/src/Component.stories.mdx, packages/popover/src/Component.test.tsx, packages/popover/src/Component.tsx, packages/popover/src/__snapshots__/Component.test.tsx.snap, packages/tooltip/src/__snapshots__/Component.test.tsx.snap
В селекте понадобилось рендерить поповер без анимации(Transition).
Возможно, будут еще кейсы, когда нужен будет поповер, но без анимации или будет достаточно css.
Добавил пропсу `withTransition`, которая позволяет отрендерить контент без Transition
=> feat(core-components-popover): can render without Transition

bin/purgecss.js, bin/purgecss.sh, package.json, yarn.lock
Добавил удаление неиспользуемых css-переменных из итоговых css-файлов.
Используется пакет `purgecss`. Удаление происходит после сборки, триггером `postbuild`.
Использовать postcss-plugin или rollup-plugin не получилось, так как у нас css-модули, и на этапе сборки `purgecss` думает, что мы вообще не используем селекторы из нашего css, и выпиливает их) По-этому добавил постобработку скриптом.
=> build: remove unused css-vars

bin/purgecss.js
`Purgecss` вырезает селекторы по атрибуту
(например `.component[data-popper-placement='left'] .arrow` в поповере).
[Issue](https://github.com/FullHuman/purgecss/issues/303)
Решение:
Добавить в whitelist селекторы, которые вырезаются. Регулярки типа `\[.+\]` не работают, по-этому можно только добавить селекторы по классу.
После того, как баг будет исправлен, можно будет whitelist удалить , а пока добавляем туда.
=> build: add purgecss whitelist

packages/tooltip/src/Component.test.tsx, packages/tooltip/src/Component.tsx
Пофиксил потерявшийся className у дочернего элемента в тултипе
=> fix(core-components-tooltip): pass target original classname

packages/button/src/Component.tsx, packages/checkbox/src/Component.tsx, packages/input/src/Component.tsx, packages/pure-input/src/Component.tsx
Не отображаются дефолтные значения пропсов в сторибуке, если компонент реализован через forwardRef
Пока что решили добавить defaultProps для таких компонентов
=> docs: add default props for storybook

packages/form-control/src/Component.stories.mdx, packages/form-control/src/Component.tsx, packages/form-control/src/__snapshots__/Component.test.tsx.snap, packages/form-control/src/index.module.css, packages/input/src/Component.stories.mdx, packages/input/src/Component.tsx, packages/input/src/__snapshots__/Component.test.tsx.snap, packages/masked-input/src/__snapshots__/Component.test.tsx.snap, packages/select/src/__snapshots__/Component.test.tsx.snap
- Нет возможности рендерить контрол в состоянии ошибки без текста
- Нет возможности скрыть иконку ошибки
https://github.com/alfa-laboratory/core-components/issues/148
- Изменил тип error на `string | boolean`
- ~Добавил пропс `hasErrorIcon`~
- Если `error=true`, то hint отрисовывается. Если `error=string`, то вместо хинта рендерится ошибка
=> feat(core-components-form-control): change errors logic

packages/checkbox-group/src/index.module.css
При импорте компонента CheckboxGroup не подцепляются стили, написанные в kebab-case
=> fix(checkbox-group): fix css classnames

packages/form-control/src/Component.tsx, packages/form-control/src/__snapshots__/Component.test.tsx.snap, packages/form-control/src/index.module.css, packages/select/src/__snapshots__/Component.test.tsx.snap, packages/themes/src/mixins/form-control/click.css
На некоторых продуктах, в частности в клике, у инпута нет иконки ошибки. 
Данный PR позволяет скрывать ее через темизацию `--form-control-error-icon-display`
Контекст https://github.com/alfa-laboratory/core-components/pull/150#discussion_r438088312
=> feat(core-components-form-control): allow to hide error icon in theme

packages/money-input/src/Component.test.tsx, packages/money-input/src/Component.tsx
Если передать неизвестную валюту (а у нас есть такой кейс)
то в placeholder будет 0 undefined
=> fix(core-components-money-input): fix default placeholder

.storybook/webpack.config.js
Добавил `preset-env` в babel, чтобы сторибук заработал в ie11
=> build: add babel-preset-env to storybook

.storybook/webpack.config.js
Убрал трансформацию классов, теперь они попадают в объект `styles` как есть. Больше не будет путаницы с `kebabcase` и `camelcase`
=> build: pass css classnames as is

packages/tooltip/src/Component.tsx
Для позиционирования тултип использует компонент `Popover`. У этого компонента есть
css-переменная `--popover-z-index`. По-дефолту она равна 1. `Popover` также используется в компоненте `Select`.
Можно добавить переопределение этой переменной в тему.
На всякий случай добавил пропсу `popoverClassName` в тултип. По этому класснейму можно будет накинуть
любой `z-index`.
=> feat(core-components-popover): add classname for tooltip popover

packages/tag/src/index.module.css
События мыши не срабатывают на задизейбленом теге.
Например есть кейс, что нужно пользователю показать почему задизейблена кнопка
https://codesandbox.io/s/quirky-cerf-l6j32?file=/src/App.js
События мыши срабатывают на задизейбленом теге
=> feat(tag): remove pointer-events none style

packages/typography/src/Component.stories.mdx
Ошика в примере импорта
Какой из импортов верный:
1) `import { Typography } from '@alfalab/core-components-typography';`
2) `import { Typography } from '@alfalab/core-components/typography';`
=> fix: fix import example

packages/button/src/index.module.css
- При `block=true` - лоудер не по центру.
- При `block=true` и пустом контенте - лоудер не по центру.
=> fix(core-components-button): fix loader position

packages/input/src/Component.tsx, packages/masked-input/src/Component.tsx
- Инпуты для унификации теперь принимают только строки. Для ввода чисел есть `AmountInput`. `string[]` - это вообще дичь.
- В onChange теперь передается `payload: { value: string }`
=> refactor: allow only string as value, add payload

packages/tabs/src/components/primary-tablist/Component.tsx, packages/tabs/src/components/primary-tablist/index.module.css
В newclick-host-ui при первом рендере ширина табов равна нулю и т.к. при ререндере вкладка не изменилась, то эффект с пересчетом стилей не запускается. Выглядит все так:
Теперь стили обновляются при каждом рендере, это поможет избежать других потенциальных проблем.
=> fix(core-components-tabs): recalc line styles on render

bin/purgecss.js, packages/amount-input/src/Component.tsx, packages/amount-input/src/__snapshots__/Component.test.tsx.snap, packages/bank-card/src/__snapshots__/Component.test.tsx.snap, packages/form-control/src/index.module.css, packages/input/package.json, packages/input/src/Component.stories.mdx, packages/input/src/Component.test.tsx, packages/input/src/Component.tsx, packages/input/src/__snapshots__/Component.test.tsx.snap, packages/input/src/index.module.css, packages/input/tsconfig.json, packages/masked-input/src/Component.tsx, packages/masked-input/src/__snapshots__/Component.test.tsx.snap, packages/phone-input/src/__snapshots__/Component.test.tsx.snap, packages/select/src/components/autocomplete/Component.stories.mdx, packages/select/src/components/field/index.module.css
- Добавлен крестик для очистки поля
- Обновлены зависимые компоненты
- Добавлены тесты
- Небольшие правки и code-style
- Инпут сделан более отзывчивым - фокус не теряется при клике в любой области поля, кроме кнопок
При очистке поля происходит событие MouseEvent<кнопка>, т.е. событие onChange не вызывается. Поэтому у controlled-инпутов нужно подписываться на onClear и очищать значение.
=> feat(core-components-input): add clear button, some improvements

packages/form-control/src/Component.test.tsx, packages/form-control/src/Component.tsx, packages/input/src/Component.test.tsx, packages/input/src/Component.tsx, packages/slider-input/src/Component.tsx
Инпут занимает не весь контрол, из-за этого появляются некликабельные области или теряется фокус:
Для этого есть обработка mouseDown внутри инпута.
Теперь фокус сохраняется только при клике в области контрола, а не всего компонента:
=> fix(core-components-input): keep focus only inside control

bin/build-themes.js, packages/themes/src/mixins/button/click.css, packages/themes/src/mixins/button/corp.css, packages/themes/src/mixins/button/mobile.css, packages/themes/src/mixins/form-control/click.css, packages/themes/src/mixins/link/click.css, packages/themes/src/mixins/pure-input/click.css, packages/themes/src/mixins/tabs/click.css, packages/themes/src/mixins/tabs/site.css, packages/themes/src/mixins/tag/click.css
Решили, что неправильно заставлять пользователей тем подключать color-mod.
- Добавил обработку color-mod
- Пофиксил неправильные цвета в темах
- Добавил импорт всех переменных во все темы
Планирую в отдельном реквесте убрать тему с `/* core vars*/` в pure-css темах
=> fix(core-components-themes): process color-mod, fix vars

.github/workflows/build.yml, bin/build.sh
Добавил ограничение на количество процессов при сборке компонентов.
Один процесс использует примерно `300МБ` оперативной памяти.
Для локальной сборки выставил ограничение в `10` процессов, для сборки на гитхабе - `5` процессов.
По времени сборки особо разницы не заметил.
=> ci: add build concurrency

packages/button/src/index.module.css
Когда `Button` используется как ссылка - выравнивание текста меняется на `left` 
См. видео https://take.ms/zkY4t
Тип кнопки не меняет выравнивание текста.
=> fix(core-components-button): add text align

packages/input/src/Component.test.tsx, packages/input/src/Component.tsx, packages/input/src/index.module.css
Частично откатил этот PR - https://github.com/alfa-laboratory/core-components/pull/294
В некоторых кейсах это вызывало проблему, поэтому убрал обработчик onMouseDown.
=> refactor(core-components-input): remove mousedown handler

packages/input/src/Component.test.tsx, packages/input/src/Component.tsx
Не показываем кнопку очистки при readOnly
=> feat(core-components-input): hide clear if input is readonly

packages/form-control/src/Component.tsx, packages/form-control/src/index.module.css, packages/input-autocomplete/src/Component.stories.mdx, packages/input-autocomplete/src/Component.tsx, packages/input-autocomplete/src/autocomplete-field/Component.tsx, packages/input/src/Component.tsx, packages/select/src/Component.stories.mdx, packages/select/src/__snapshots__/Component.test.tsx.snap, packages/select/src/__snapshots__/utils.test.tsx.snap, packages/select/src/components/arrow/index.module.css, packages/select/src/components/base-select/Component.tsx, packages/select/src/components/base-select/index.module.css, packages/select/src/components/field/Component.tsx, packages/select/src/components/field/index.module.css, packages/select/src/components/native-select/Component.tsx, packages/select/src/components/optgroup/index.module.css, packages/select/src/components/option/Component.tsx, packages/select/src/components/options-list/index.module.css, packages/select/src/components/virtual-options-list/index.module.css, packages/select/src/typings.ts, packages/select/src/utils.test.tsx, packages/select/src/utils.ts
1. Понадобилось вешать `onClick` и `onMouseDown` на инпут, но не на сам `<input>`, а не весь контрол. Поэтому перенес ...restProps в `FormControl` и добавил явные обработчики в `Input`
2. Небольшой рефакторинг селекта и автокомплита, убрал лишний код и немного упростил. Надеюсь, что это последний раз 🧠 💥 
3. После интеграции в клик, появилось желание изменить структуру данных и упростить работу с компонентом.
Предлагаю сделать следующие изменения:
3.1. Данные принимать в таком виде:
```tsx
export type OptionShape = {
/**
* Текстовое представление пункта. Единственное необходимое поле
*/
key: string;
/**
* Контент, который будет отрисован в выпадающем списке и в поле при выборе
*/
content?: ReactNode;
/**
* Блокирует данный пункт для выбора
*/
disabled?: boolean;
/**
* Дополнительные …
```
=> refactor(core-components-select): inputs & types

packages/confirmation/src/component.stories.mdx, packages/confirmation/src/component.tsx, packages/confirmation/src/components/code-input/component.tsx, packages/confirmation/src/components/code-input/index.module.css, packages/confirmation/src/components/sign-confirmation/component.tsx
- отцентрировал инпуты
- добавил пропсу `errorText`
BREAKING CHANGE: пропса `error` теперь `boolean`
**Мотивация**: бывают кейсы когда не нужен текст ошибки и требуется только подсветка инпутов
=> feat(core-components-confirmation): separate error and error text

packages/form-control/src/index.module.css, packages/themes/src/mixins/form-control/click.css
При выбранной теме "click" у disabled form-control никак не меняется визуальное отображение
1. Открыть компонент формы, использующий form-control, например, селект
2. Выбрать тему "click"
3. Проставить галку disabled в knobs
Внешний вид индицирует о заблокированности контрола
=> feat(core-components-form-control): set opacity in disabled state

packages/slider-input/src/Component.tsx, packages/slider-input/src/__snapshots__/Component.test.tsx.snap, packages/slider-input/src/index.module.css
— сделал текст внутри инпута жирным и моноширинным
Вообще стоит отдельным PR изменить стили в инпуте и withSuffix, чтобы они наследовали стили для текста. Но пока проще просто накинуть немножко грязных стилей)
=> refactor(slider-input): update input styles

packages/circular-progress-bar/src/index.module.css
Заставляю контейнер занимать всю доступную ширину
fix #394
=> fix(circular-progress-bar): fix label width

packages/select/src/Component.stories.mdx, packages/select/src/typings.ts, packages/select/src/utils.test.tsx, packages/select/src/utils.ts
Как оказалось — в одних кейсах удобнее в `selected` передавать ключи, а в некоторых других сами элементы из `options`.
Теперь селект поддерживает оба варианта
=> feat(select): allow to use options as selected value

packages/mq/src/Component.test.tsx, packages/mq/src/useMatchMedia.test.tsx, packages/mq/src/useMatchMedia.tsx, packages/select/src/components/arrow/index.module.css
- Как оказалось addEventListener и removeEventListener не поддерживаются в IE для MediaQueryList.
- Пофиксил позицию стрелки селекта в IE
=> fix(mq): use addListener and removeListener

packages/amount-input/src/Component.stories.mdx, packages/amount-input/src/Component.tsx
В `AmountInput` захардкожено максимальное количество символов до запятой.
Попробовать ввести в `AmountInput` 999 999 999 999.
Можно дать пользователю вводить более 9 символов до запятой. 
prop integerLength - аналог [integerLength из MoneyInput](https://github.com/alfa-laboratory/arui-feather/blob/master/src/money-input/money-input.tsx#L60)
=> Добавляет возможность изменять максимальное количество символов до запятой в AmountInput

bin/build-themes.js, packages/dark-theme-styles-injector/package.json, packages/dark-theme-styles-injector/src/component.tsx, packages/dark-theme-styles-injector/src/index.ts, packages/dark-theme-styles-injector/tsconfig.json, packages/themes/src/mixins/colors/colors-bluetint.css, packages/themes/src/mixins/colors/colors-indigo.css, tools/rollup/process-css.js, tools/update-colors.js, typings/themes.d.ts
- Добавил генерацию миксинов, в которых светлые цвета заменяются на темные
- Добавил сами миксины: `themes/src/mixins/colors/`
- Добавил компонент `DarkThemeStylesInjector`, который вставляет переопределение цветов на страницу
Пример использования компонента `DarkThemeStylesInjector` в [паспорте](http://git.moscow.alfaintra.net/projects/PAS/repos/retail-passport-ui/pull-requests/686/overview)
=> feat(themes): add dark theme mixins

packages/circular-progress-bar/src/index.module.css
Ссылка на figma https://www.figma.com/file/KlFOLLkKO8rtvvQE3RXuhq/Click-Library?node-id=11501%3A44539
Сделал в соответствии с макетом.
Было:
Стало:
=> fix(circular-progress-bar): change max-height

packages/attach/src/Component.tsx, packages/bank-card/src/Component.tsx, packages/notification/src/Component.tsx, packages/picker-button/src/field/Component.tsx, rollup.config.js
- поменял импорты иконок
- удалил путь до `esm-модулей` из сборки `cssm`, так как для корректной работы нужно добавлять еще одну сборку
=> fix: change icons imports paths

packages/calendar/src/useCalendar.ts, packages/calendar/src/utils.ts
Если передать в пропсе maxDate дату года, > чем new Date(), то в списке годов следующих за текущим не появится:
https://p52.f0.n0.cdn.getcloudapp.com/items/Koul19dE/b9883993-b1ff-44b2-a439-9a96670a802d.gif?source=viewer&v=81dce36bdb03d84a7a8c81cf3cad6923
1. Пробросить в maxDate год больший, чем текущий
2. Нажать на кнопку выбора года
Доступны все года в интервале
- OS: MacOS
- Version: 10
- OS: iOS 10
- Version: 65
=> fix(calendar): set max date to years calculation

packages/themes/src/default.css
fix #442
Добавил пропущенный импорт css переменных из colors-addons.css
=> fix(themes): add missing variables import

packages/tooltip/src/Component.test.tsx, packages/tooltip/src/Component.tsx
Пофиксил баг: Тултип клонирует дочерние элементы и навешивает на них обработчики (onClick/onMouseOver/onMouseOut/onTouchStart).
Если на этом элементе уже были эти обработчики, то они сейчас не вызываются.
+ поправил тест, там был warning
=> fix(tooltip): execute tooltip's target missing callbacks

package.json, packages/button/src/Component.stories.mdx, packages/picker-button/src/__snapshots__/Component.test.tsx.snap, packages/picker-button/src/field/Component.tsx, packages/picker-button/src/field/index.module.css, yarn.lock
Иконки заменены на одноцветные, что позволило убрать костыль с прозрачностью svg
=> feat(picker-button): simplify picker-button using colorless icons

packages/input-autocomplete/src/Component.stories.mdx, packages/select/src/components/base-select/Component.tsx, packages/select/src/components/options-list/Component.tsx, packages/select/src/components/options-list/index.module.css, packages/select/src/components/virtual-options-list/Component.tsx, packages/select/src/components/virtual-options-list/index.module.css, packages/select/src/typings.ts, packages/select/src/vars.css
Добавил в селект пропсу `optionsListEmptyPlaceholder`.
Нужна для отображения плейсхолдера `Ничего не найдено` в автокомплите.
=> feat(select): add empty list placeholder prop

packages/amount-input/src/__snapshots__/Component.test.tsx.snap, packages/bank-card/src/__snapshots__/Component.test.tsx.snap, packages/calendar-input/src/__snapshots__/Component.test.tsx.snap, packages/calendar-range/src/__snapshots__/Component.test.tsx.snap, packages/form-control/src/Component.test.tsx, packages/form-control/src/Component.tsx, packages/input/src/Component.test.tsx, packages/input/src/Component.tsx, packages/input/src/__snapshots__/Component.test.tsx.snap, packages/intl-phone-input/src/__snapshots__/component.test.tsx.snap, packages/masked-input/src/__snapshots__/Component.test.tsx.snap, packages/phone-input/src/__snapshots__/Component.test.tsx.snap, packages/select-with-tags/src/components/tag-list/component.tsx, packages/select/src/components/field/Component.tsx, packages/slider-input/src/__snapshots__/Component.test.tsx.snap, packages/textarea/src/Component.test.tsx, packages/textarea/src/Component.tsx, packages/with-suffix/src/__snapshots__/Component.test.tsx.snap
Привел инпут к единообразию с остальными компонентами. Лучше это сейчас сделать, пока еще нет активного использования либы
BREAKING CHANGE: может затронуть кастомную стилизацию контролов
=> feat: add fieldClassName

.github/workflows/npm-publish.yml, bin/publish-root-package.sh, packages/release.config.js
Проблема в том что надо руками постоянно выпускать релизы, хотя это по идее должно происходить на каждое изменеие мастера и версия должня высчитываться исходя из сообщений коммитов.
ПР решает эту проблему, а именно semantic-release сам меняет версии в package.json и пушит в npm, так же пушит все подпокеты с верными версиями в npm.
Для примера как работает можно посмотреть [тестовый репозиторий,](https://github.com/IBelyaev/core-components-test) так же могу дать права чтобы руками там поменять код и посмотреть, как все работает.
_Чтобы получить доступ - пишите мне в слак._
=> fix: adds semantic release configs again

bin/build.sh
Пофиксил проблему попадания папки `dist` в сборку, если сборка запущена в `github-actions`.
=> build: fix copying css packages

packages/button/src/Component.stories.mdx, packages/button/src/Component.tsx, packages/button/src/index.module.css, packages/themes/src/mixins/button/corp.css
Во-первых, это красиво.
Дополнительный вид [с полупрозрачным фоном](https://www.figma.com/file/KlFOLLkKO8rtvvQE3RXuhq/Click-Library?node-id=14001%3A44930).
Также фиксит hover/active для secondary/filled кнопок после изменения цвета specialbg-component (для полупрозрачного цвета нужен blenda вместо shade).
=> feat(button): transparent view

packages/select/src/components/base-select/index.module.css
Проблема сафари overflow: hidden + border-radius
Открыть сафари
Открыть селект с большим кол-вом опций
Увидеть, что, из-за бага сафари у option-list нет скругления. Потому как overflow: hidden + border-radius не работают в сафари, как ожидается
** ![image](https://user-images.githubusercontent.com/12587757/106161310-de273700-6197-11eb-906f-67ec46739a31.png) ** | ** ![image](https://user-images.githubusercontent.com/12587757/106161227-c5b71c80-6197-11eb-9d90-0f2239ab5614.png) ** | 
Фиксится при помощи transform: translateZ(0) либо will-change: transform для современных браузеров.
=> fix(select): fix safari overflow bug

packages/calendar-range/src/Component.test.tsx, packages/calendar-range/src/Component.tsx, packages/calendar-range/src/index.module.css
> Говорят, при выборе диапазона бывает нужно выбрать один день, такие дела :)
- Второе нажатие выбирает конечную дату
- Третье нажатие на один и тот же день сбрасывает выбор
=> feat(calendar-range): allow to select one-day range

.github/workflows/npm-publish.yml, bin/publish-ci.sh, package.json
Немного поменял процесс публикации:
- рутовый пакет релизится через `semantic-release`
- подпакеты релизятся через `lerna`
=> ci: change ci workflow

packages/notification/src/Component.stories.mdx, packages/notification/src/Component.tsx, packages/notification/src/__snapshots__/Component.test.tsx.snap, packages/notification/src/index.module.css, packages/themes/src/mixins/toast-plate/click.css, packages/toast-plate/src/__snapshots__/component.test.tsx.snap, packages/toast-plate/src/component.stories.mdx, packages/toast-plate/src/component.tsx, packages/toast-plate/src/index.module.css
* notification: ширина фиксируется только у контентной области, без учёта кнопкок и отступов
* toast-plate: добавлен contentClassName для контроля ширины контентной области, чуть отрефачены стили
BREAKING CHANGE: --notification-desktop-width var removed
=> Люблю тосты

packages/select/src/components/base-select/index.module.css
Не корректно работало обрезание текста для _option_. Слишком большой контент с `white-space: nowrap; ` выезжал за границы контейнера (формы например). Особенность: если на _option_ висит `display: grid;`, то такого эффекта не наблюдается.
Текст обрезается, всё отображается корректно.
- OS: MacOS
=> fix(select): min width bug

packages/select/src/components/options-list/Component.tsx, packages/select/src/components/virtual-options-list/Component.tsx, packages/select/src/utils.ts
Пересчитываем высоту меню, если кол-во пунктов меню изменилось. Актуально для автокомплита
=> fix(select): recalc height on options changed

packages/select-with-tags/src/components/tag-list/index.module.css
Не открывается селект с тэгами при клике на внутреннее поле
1. Выбрать autocomplete=false
2. Потыкать на плейсхолдер
Селект должен открываться\закрываться
При autocomplete=false, плейсхолдер рендерится отдельным элементом и [условие](https://github.com/alfa-laboratory/core-components/blob/master/packages/select-with-tags/src/components/tag-list/component.tsx#L114) работает не совсем корректно
=> fix(select-with-tags): remove pointer events from placeholder

package.json, tools/rollup/core-components-typings-resolver.js, yarn.lock
Поменял регулярку для поиска импортов типов в рут-пакете. 
Протестить сборку можно `@alfalab/core-components@13.1.1-beta.0`
=> fix: fix types importing in root package

packages/select/src/Component.stories.mdx, packages/select/src/components/base-select/Component.tsx, packages/select/src/components/option/index.module.css, packages/select/src/typings.ts
Добавил возможность управлять шириной выпадающего меню. 
Оказалось, что это частый кейс, когда нужно обрезать пункты меню по ширине поля
=> feat(select): add options-list width

packages/calendar-input/src/Component.test.tsx, packages/calendar-input/src/Component.tsx
fix #591 
Добавил только тоггл по enter, а не по введенному значению.
Закрытие после введенного валидного значения усложнит логику компонента и может сделать его менее предсказуемым. Думаю enter'а будет достаточно
=> feat(calendar-input): toggle calendar on enter

packages/select-with-tags/src/utils/match.ts
Пофиксил недоступное свойство объекта(includes) в браузере IE11 
Дока
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes
- OS: Windows
- Browser: IE
- Version: 11
=> fix(select-with-tags): changed includes method for IE11 support

packages/calendar-input/src/Component.test.tsx, packages/calendar-input/src/Component.tsx
Небольшой фикс, позволяющий задавать все свойства календаря через calendarProps.
Чтобы не делать мажорку, не стал убирать minDate, maxDate и offDays из пропсов CalendarInput. Теперь задать можно и напрямую и через calendarProps
Сейчас вот такой код не работает:
```tsx
<CalendarInput
calendarProps={{
minDate: 1622408400000,
maxDate: 1623358800000,
offDays: [1622408400000, 1622840400000, 1622926800000],
}}
/>
```
=> fix(calendar-input): allow to pass all props via calendarProps

packages/button/src/index.module.css
Лоудер немного приуныл в IE11 :(
=> fix(button): loader position in ie

packages/base-modal/src/Component.test.tsx, packages/base-modal/src/Component.tsx
Если на странице есть скроллбар, то модалка при закрытии скачет влево. 
Перенес восстановление стилей контейнера в фазу exited
=> fix(modal): restore styles after exited

packages/confirmation/src/Component.test.tsx, packages/confirmation/src/__snapshots__/Component.test.tsx.snap, packages/confirmation/src/component.tsx, packages/confirmation/src/components/sign-confirmation/component.tsx
Добавил возможность использовать signTitle prop как строку - так и jsx
- чтобы иметь возможность вставлять кастомный компонент вместо строки.
=> feat(confirmation): set up signTitle prop as slot

packages/dropzone/src/index.module.css
Пофиксил баг
>  всё что внутри дропзоны перекрывается невидимым оверлеем и становится некликабельным
=> fix(dropzone): add pointer-events none to overlay

packages/masked-input/src/Component.tsx
В пакете text-mask-core лежат кривые и неполные типы, поэтому пришлось написать самим. Но кастомные типы не попадают в сборку и создают проблемы. 
Пока что просто продублировал типы в компоненте.
Если кто-то знает, как сделать нормально — подскажите плз
=> fix(masked-input): inline module types

packages/select/src/utils.ts
[Чинит такой кейс](https://alfa-laboratory.github.io/core-components/master/?path=/docs/%D0%B3%D0%B0%D0%B9%D0%B4%D0%BB%D0%B0%D0%B9%D0%BD%D1%8B-%D0%BF%D0%B5%D1%81%D0%BE%D1%87%D0%BD%D0%B8%D1%86%D0%B0--page/code=const%20options%20%3D%20%5B%0A%20%20%20%20%7B%20key%3A%20%271%27%2C%20content%3A%20%27Neptunium%20Neptunium%20Neptunium%20Neptunium%20Neptunium%20NeptuniumNeptunium%20Neptunium%20NeptuniumNeptunium%20Neptunium%20NeptuniumNeptunium%20Neptunium%20NeptuniumNeptunium%20Neptunium%20NeptuniumNeptunium%20Neptunium%20NeptuniumNeptunium%20Neptunium%20NeptuniumNeptunium%20Neptunium%20Neptunium%27%7D%2C%0A%5D%3B%0A%0Arender(%0A%3Cdiv%20style%3D%7B%7B%20width%3A%20320%20%7D%7D%3E%0A%20%20%3CInputAutocomplete%20options%3D%7Boptions%7D%20label%3D%22select%22%20block%3D%7Btrue%7D%20optionsListWidth% …
=> fix(select): calc height in effect

packages/select/package.json, packages/select/src/Component.stories.mdx, packages/select/src/index.ts, packages/select/src/presets/index.ts, packages/select/src/presets/useSelectWithLoading/hook.tsx, packages/select/src/presets/useSelectWithLoading/index.module.css, packages/select/tsconfig.json
Скелетная загрузка для селекта. 
Одно из условий — больше не раздувать сам селект.
Посчитал, что хорошей идеей будет подготовить пресеты с пропсами, которые превратят селект в то, что нужно.
=> feat(select): add useSelectWithLoading preset

packages/calendar-with-skeleton/src/Component.tsx, packages/calendar-with-skeleton/src/__snapshots__/Component.test.tsx.snap, packages/calendar-with-skeleton/src/index.module.css
[Демка с багами](https://alfa-laboratory.github.io/core-components/master/?path=/docs/%D0%B3%D0%B0%D0%B9%D0%B4%D0%BB%D0%B0%D0%B9%D0%BD%D1%8B-%D0%BF%D0%B5%D1%81%D0%BE%D1%87%D0%BD%D0%B8%D1%86%D0%B0--page/code=const%20CustomCalendar%20%3D%20React.forwardRef((props%2C%20ref)%20%3D%3E%20%7B%0A%20%20const%20%5BcalendarVisible%2C%20setCalendarVisible%5D%20%3D%20React.useState(false)%3B%0A%0A%20%20React.useEffect(()%20%3D%3E%20%7B%0A%20%20%20%20setTimeout(()%20%3D%3E%20setCalendarVisible(true)%2C%201500)%3B%0A%20%20%7D%2C%5B%5D)%3B%0A%0A%20%20return%20%3CCalendarWithSkeleton%20calendarVisible%3D%7BcalendarVisible%7D%20ref%3D%7Bref%7D%20%7B...props%7D%20%2F%3E%0A%7D)%3B%0A%0Afunction%20Example()%20%7B%0A%20%20%20%20const%20%5Bvisible%2C%20setVisible%5D%20%3D%20React.useState(false)%3B%0A%20%20%20%2 …
=> fix(calendar-with-skeleton): ref & six weeks height issues

bin/build-themes.js, packages/dark-theme-styles-injector/src/component.tsx
Добавил возможность устанавливать, по какому селектору будет применяться инвертированный режим
=> feat(dark-theme-styles-injector): add prop for selector

packages/intl-phone-input/src/component.test.tsx, packages/intl-phone-input/src/component.tsx, packages/intl-phone-input/src/utils/format-phone-with-unclearable-country-code.test.ts, packages/intl-phone-input/src/utils/format-phone-with-unclearable-country-code.ts, packages/intl-phone-input/src/utils/get-phone-diff.test.ts, packages/intl-phone-input/src/utils/get-phone-diff.ts
Если каретка стоит до или внутри кода страны, пользователь начинает вводить символы, то каретка перемещается в конец кода страны
- Открыть IntlPhoneInput
https://alfa-laboratory.github.io/core-components/master/?path=/story/%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B--intl-phone-input
Knob clearableCountryCode - false
- Поставить каретку внутри/до кода страны
- Ввести цифру
Если каретка стоит до или внутри кода страны и пользователь начинает вводить символы, то символы должны добавляться после кода страны
=> fix(intl-phone-input): format input value

packages/confirmation/src/Component.test.tsx, packages/confirmation/src/component.tsx, packages/confirmation/src/components/countdown/component.tsx, packages/confirmation/src/components/sign-confirmation/component.tsx
Сейчас `buttonRetryText` меняет текст на кнопке, которая находится на экране помощи (необходимо нажать на псевдо-ссылку "Не приходит сообщение?"), что, на мой взгляд, не совсем очевидно, т.к. есть еще кнопка которая запрашивает новый код после окончания таймера.
Добавляю `buttonReturnText` для кнопки на экране помощи и переназначаю `buttonRetryText` на кнопку, которая покажется после окончания таймера.
=> feat(confirmation): add property for change retry button text

packages/skeleton/src/Component.stories.mdx, packages/skeleton/src/index.module.css, packages/skeleton/src/stories.module.css
Изначально сделали inline-block, и казалось норм, т.к. можно обернуть любой контент и он будет нужной ширины.
Но:
1. Прилетела [ишья](https://github.com/alfa-laboratory/core-components/issues/704).
2. По факту, в известных нам кейсах никто не оборачивает контент.
BREAKING CHANGE: inline-block changes to block
=> feat(skeleton): add display var, change default to block

packages/popover/src/Component.tsx, packages/toast/src/component.tsx, packages/tooltip/package.json, packages/tooltip/src/Component.test.tsx, packages/tooltip/src/Component.tsx, packages/tooltip/src/__snapshots__/Component.test.tsx.snap
Возник кейс, когда потребовался `ref` на элемент-обертку.
=> feat(tooltip): add target ref property

packages/input/src/Component.tsx
В этом пр исправляется проблема лейбла наезжающего на картеку инпута с автофокусом.
Похоже вся проблема в том, что состояние фокуса хранится не только в доме, но и в `useFocus` и
в `const [focused, setFocused] = useState()`
Отсюда следует что оно может расходится. Что и происходит при монтировании <Input autoFocus />, стейт компонента в расфокусе а дом-нода в фокусе
=> fix(input): autofocus

packages/amount-input/src/Component.test.tsx, packages/amount-input/src/Component.tsx, packages/amount-input/src/docs/Component.stories.mdx
Добавляет возможность ограничить ввод только целыми числами через `integersOnly`. 
Применяется только к вводу
=> feat(amount-input): add integers only mode

packages/intl-phone-input/src/component.tsx, packages/intl-phone-input/src/usePreventCaretReset.ts, packages/intl-phone-input/src/utils/format-phone-with-unclearable-country-code.test.ts, packages/intl-phone-input/src/utils/format-phone-with-unclearable-country-code.ts
* Каретка прыгает в конец строки при удалении символа
* Хочется чтобы при выделении кода страны (вариант с нестираемым кодом страны) и вводе цифры мобильного он появлялась после кода страны(как в phoneInput). На данный момент вводимая цифра игнорируется 
Шаги для воспроизведения:
1. Перейти во вкладку "Платежи и переводы" -> "Мобильная связь"
2. Ввести полностью номер телефона
3. Удалить не последний символ из номера
Ожидаемый результат: удалится символ, каретка останется на его месте
Фактический результат: удалится символ, каретка переместится в конец строки
P.S. По наблюдению, баг вопроизводится только при условии, что введено 7+ цифр (например если ввести +7 999 999 и удалить символ, то все придет к ожидаемому результату, а если ввести +7 999 999 9... , то баг воспроизведется)
=> Доработки IntlPhoneInput

packages/select/src/presets/useLazyLoading/hook.tsx
Небольшой фикс: неверно была проставлена пропса, из-за которой выбранная опция никогда не будет индицироваться
=> fix(select): remove wron prop passed into renderOption method

packages/button/src/Component.tsx, packages/icon-button/src/Component.tsx
Previously, if you use IconButton like link - TS used to swear at the absence of the 'target'
property of IconButton.
При нажатии на кнопку 'создать отчет' ничего не происходит
1. Перейти на страницу '...'
2. Нажать на кнопку '...'
При нажатии на кнопку должно появится модальное окно
- OS: MacOS
- Version: 10
- OS: iOS 10
- Version: 65
=> feat(icon-button): added 'target' attribute, when IconButton is link

packages/intl-phone-input/src/usePreventCaretReset.ts
#806
Поправлен первый кейс
> Кейс первый
> если отредактировать номер телефона (удалить не последний символ и вести новый), то каретка перепрыгнет в конец номера, ожидаемое поведение: каретка останется там, где происходило редактирование.
=> fix(intl-phone-input): fix carret position on backspace

packages/confirmation/src/__image_snapshots__/confirmation-interactions-tests-open-don-t-receive-sms-snap.png, packages/confirmation/src/components/code-input/component.tsx, packages/confirmation/src/components/code-input/index.module.css, packages/confirmation/src/docs/Component.stories.mdx
Код из 8 символов не влезает на мобилках, делаем его более компактным
=> feat(confirmation): compact code-input if slotsCount > 6

packages/modal/src/Component.desktop.tsx, packages/modal/src/Component.mobile.tsx
Нельзя задать className для Backdrop компонента Modal
=> fix(modal): Fix spreading backdrop props to BaseModal component

packages/select/src/components/base-select/Component.tsx, packages/select/src/typings.ts
Добавил настройку z-index для поповера
Необходима для совместимости с компонентами arui-feather
Например, у sidebar'а из arui-feather по умолчанию [z-index=1001](https://github.com/alfa-laboratory/arui-feather/blob/master/src/sidebar/sidebar.css#L28)
=> feat(select): add zIndexPopover property

packages/skeleton/src/Component.tsx, packages/skeleton/src/__snapshots__/Component.test.tsx.snap
При переключении видимости компонента Skeleton, его содержимое полностью ре-рендерится. 
Это приводит к тому, что содержащиеся в нем изображения загружаются повторно. Как итог, становится затруднительным поймать момент, когда изображения под скелетоном полностью загружены, так как событие `onLoad` у таких изображений срабатывает дважды.
Причина полного рендера кроется в разных корневых элементах в зависимости от видимости скелетона (`div` / `React.Fragment`). Чтобы этого избежать, в этом PR в обоих случаях используется  `div`
Демо: https://codesandbox.io/s/skeleton-demo-y7quf . Текущее поведение: событие onLoad выполняется дважды
Событие onLoad выполняется один раз - в конце загрузки изображение
=> fix(skeleton): prevent component unmount

packages/toast-plate/src/index.module.css
В нотификациях ломается перенос слов
1. Вызвать нотиф с текстом, например: 'Вебирите доступную дату получения'
2. Перенос будет осуществлен с разбиением слова "получения"
Перенос происходит только на границах слов
=> fix(notification): убрал word-break: break-all

packages/calendar-input/src/Component.tsx
Добавил пропс zIndexPopover для Popover'а компоненты CalendarInput.
Иногда есть необходимость изменить значение z-index Popover'а по умолчанию, чтобы календарь был поверх всех компонентов.
=> fix(calendar-input): fixes CalendarInput Popover z-index

packages/icon-view/src/components/circle/component.tsx, packages/icon-view/src/components/super-ellipse/component.tsx
По чистой случайности заметил, что типы как-то криво собираются, пришлось явно указывать `children` в пропсах.
Ниже скриншот, как типы собирались до фикса (там нет children):
=> fix(icon-view): fix types

packages/picker-button/src/Component.tsx
Now picker-button size prop can take values: 'xxs', 'xs', 's', 'm', 'l', 'xl'
fix #986
=> fix(picker-button): fixed type of picker-button size prop

packages/skeleton/src/Component.tsx
Если `visible !== true`, то `dataTestId` не передается в `div`
=> fix(skeleton): added dataTestId

packages/radio-group/src/Component.test.tsx, packages/radio-group/src/Component.tsx, packages/radio-group/src/__snapshots__/Component.test.tsx.snap
Добавлен отсутствубщий атрибут `value` для тега `input`, который рендерится внутри компонента `RadioGroup` при использовании с компонентом `Tag`.
fixes #1031
=> fix(radio-group): add missing 'value' attribute to 'input' tag

packages/table/src/components/table/index.module.css, packages/table/src/components/thead-cell/index.module.css, packages/table/src/components/tsortable-head-cell/index.module.css
1. Фикс иконок
2. Выравнивание по верхнему краю (пришлось добавить 1px margin-top иконке)
3. Защитный отступ 4px у ячеек шапки
4. Автоскролл у враппера
Код потестить
```
const data = [
{
id: 1,
date: "27.06.2022",
title: "ИП Жуков Валерий Сергеевич",
subtitle: "Услуги по ремонту за июнь, НДС не облагается",
sum: 21000000,
},
{
id: 2,
date: "28.06.2022",
title: 'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "МОБИЛСТИЛ"',
subtitle:
"Оказание услуг по договору № 26/09 на основании акта № 1450 от 30 июня 2020 года, в т.ч. НДС 18%",
sum: 10002030,
},
{
id: 3,
date: "29.06.2022",
title: 'ООО "КОРПУС-ИТ"',
sum: 3000069,
},
{
id: 4,
date: "30.06.2022",
title: "MasterBrok",
sum: 42130000,
},
];
render(() => {
const [sortKey, setSortKey] = React.useState(undefined);
const [isSortedDesc, setIsSortedDesc] …
```
=> fix(table): update styles
